import { Boundary } from '../models/autogenerated/Boundary'
import { DiagramElementSpec } from '../models/autogenerated/DiagramElementSpec'
import { DiagramSpec } from '../models/autogenerated/DiagramSpec'
import { ElementData } from '../models/autogenerated/ElementData'
import { RenderElementsOptions } from '../rendering-system/diagram-renderer'
import { BOUNDARY, BOX } from '../styles/style-constants'
import { C4BaseComponentOptions } from './C4BaseComponent'
import C4BaseElasticContainer, {
  C4BaseElastiContainerComponent,
} from './C4BaseElasticContainer'

export const C4Boundary = (
  data: Boundary,
  elementSpec: DiagramElementSpec,
  diagramSpec: DiagramSpec,
  autoLayout: Record<string, ElementData>,
  options: Partial<C4BaseComponentOptions> | undefined,
  renderElementsOptions: RenderElementsOptions | undefined,
): C4BaseElastiContainerComponent | undefined => {
  const defaultOptions: C4BaseComponentOptions = {
    bgColor:
      renderElementsOptions?.diagramsThemeSettings?.bg_color_boundary ??
      BOX.COLORS.BG_COLOR_BOUNDARY,
    borderColor:
      renderElementsOptions?.diagramsThemeSettings?.border_color_boundary ??
      BOX.COLORS.BORDER_COLOR_BOUNDARY,
    textColor:
      renderElementsOptions?.diagramsThemeSettings?.text_color_boundary ??
      BOX.COLORS.TEXT_COLOR_BOUNDARY,
    strokeDashArray: BOUNDARY.SIZES.STROKE_DASH_ARRAY,
  }
  const enrichedOptions: C4BaseComponentOptions = {
    ...defaultOptions,
    ...options,
  }
  return C4BaseElasticContainer(
    data,
    elementSpec,
    diagramSpec,
    autoLayout,
    enrichedOptions,
    renderElementsOptions,
  )
}

export default C4Boundary
