import { DeploymentNode } from '../models/autogenerated/DeploymentNode'
import { DiagramElementSpec } from '../models/autogenerated/DiagramElementSpec'
import { DiagramSpec } from '../models/autogenerated/DiagramSpec'
import { BOX } from '../styles/style-constants'
import { C4BaseComponentOptions } from './C4BaseComponent'
import C4BaseElasticContainer, {
  C4BaseElastiContainerComponent,
} from './C4BaseElasticContainer'

export const C4DeploymentNode = (
  data: DeploymentNode,
  elementSpec: DiagramElementSpec,
  diagramSpec: DiagramSpec,
  options?: Partial<C4BaseComponentOptions>
): C4BaseElastiContainerComponent | undefined => {
  const defaultOptions: C4BaseComponentOptions = {
    bgColor: BOX.COLORS.BG_COLOR_DEPLOYMENT_NODE,
    borderColor: BOX.COLORS.BORDER_COLOR_DEPLOYMENT_NODE,
    textColor: BOX.COLORS.TEXT_COLOR_DEPLOYMENT_NODE,
  }
  const enrichedOptions: C4BaseComponentOptions = {
    ...defaultOptions,
    ...options,
  }
  return C4BaseElasticContainer(data, elementSpec, diagramSpec, enrichedOptions)
}

export default C4DeploymentNode
