// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AIDiagramGenElementType } from "./AIDiagramGenElementType";

export interface AIDiagramGenElement { alias?: string, label?: string, description?: string, technology?: string, element_type?: AIDiagramGenElementType, from_alias?: string, to_alias?: string, }