// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSearchCategory } from "./FileSearchCategory";

export interface FileSearchResult { line_content: string, line_number: number, category: FileSearchCategory, path: string, }