// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSearchResult } from "./FileSearchResult";

export interface FileSearchResults { results: Record<string, Array<FileSearchResult>>, count: number, reached_limit: boolean, }