// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagram } from "..\\..\\..\\..\\..\\libs\\c4-model-ui-kit\\src\\models\\autogenerated\\Diagram";

export type HookData = { Diagram: Diagram };