// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectLibrary } from "./ProjectLibrary";
import type { ProjectSettings } from "./ProjectSettings";

export interface Project { project_settings: ProjectSettings, project_library: ProjectLibrary, }