// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { C4Elements } from "./C4Elements";

export interface ProjectLibrary { elements: C4Elements, }