// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagramsThemeSettings } from "..\\..\\..\\..\\..\\libs\\c4-model-ui-kit\\src\\models\\autogenerated\\DiagramsThemeSettings";

export interface ThemesSettings { diagrams_theme_settings?: DiagramsThemeSettings, }