import { C4BaseComponentData } from '../components/C4BaseComponent'
import {
  DIAGRAM_EXTERNAL_LINK_PROTOCOLS,
  DiagramExternalLinkVariables,
} from '../constants/diagram-link'
import { Component } from '../models/autogenerated/Component'
import { Container } from '../models/autogenerated/Container'
import { DiagramElementType } from '../models/autogenerated/DiagramElementType'
import { SoftwareSystem } from '../models/autogenerated/SoftwareSystem'
import {
  componentDiagramElement,
  containerDiagramElement,
  softwareSystemDiagramElement,
} from './diagram-helper'

export function isExternalLink(diagramLink: string) {
  return DIAGRAM_EXTERNAL_LINK_PROTOCOLS.some((protocol) =>
    diagramLink.startsWith(protocol),
  )
}

export function linkLabelFromExternalLink(diagramLink: string) {
  try {
    const url = new URL(diagramLink)
    return `Open Link ${url.host.replace('www.', '')}`
  } catch (e) {
    return 'Open Link'
  }
}

export function externalLinkVariableToPlaceholder(
  variable: DiagramExternalLinkVariables,
) {
  return `<${variable.toString().toUpperCase()}>`
}

export function replaceExternalLinkVariables(
  diagramLink: string,
  rawData?: C4BaseComponentData,
) {
  let newDiagramLink = `${diagramLink}`
  for (const variable in DiagramExternalLinkVariables) {
    switch (variable) {
      case DiagramExternalLinkVariables.Alias.toString(): {
        if (
          newDiagramLink.includes(
            externalLinkVariableToPlaceholder(
              DiagramExternalLinkVariables.Alias,
            ),
          ) &&
          rawData?.base_data?.alias
        ) {
          newDiagramLink = newDiagramLink.replace(
            new RegExp(
              externalLinkVariableToPlaceholder(
                DiagramExternalLinkVariables.Alias,
              ),
              'gi',
            ),
            rawData.base_data.alias,
          )
        }
      }
    }
  }
  return newDiagramLink
}

export function linkableDiagramElement(element: DiagramElementType) {
  return (
    (softwareSystemDiagramElement(element) as SoftwareSystem | undefined) ||
    (containerDiagramElement(element) as Container | undefined) ||
    (componentDiagramElement(element) as Component | undefined)
  )
}
