import { AddElementTag } from '../models/autogenerated/AddElementTag'
import { generateAddElementTagKey } from './diagram-helper'

export const TAGS_SEPARATOR = '+'

export function parseTags(tags: string | undefined) {
  return tags?.split(TAGS_SEPARATOR)
}

export function buildTags(tags: string[] | undefined) {
  return tags && tags.length > 0 ? tags.join(TAGS_SEPARATOR) : undefined
}

export function getCustomTagsStyle(
  tags: string[] | undefined,
  elementsTags: Record<string, AddElementTag> | undefined,
) {
  if (tags && elementsTags) {
    const filteredElementsTags: AddElementTag[] = []
    for (const tag of tags) {
      const key = generateAddElementTagKey(tag)
      const elementTag = elementsTags[key]
      if (elementTag) {
        filteredElementsTags.push(elementTag)
      }
    }
    if (filteredElementsTags.length > 0) {
      return Object.assign({}, ...filteredElementsTags) as AddElementTag
    }
  }
  return
}
