import { Node as NodeType, ReactFlowInstance } from '@xyflow/react'
import { v4 as uuidV4 } from 'uuid'

import { DiagramElementSpec } from '../../../models/autogenerated/DiagramElementSpec'
import { RenderElementsOptions } from '../../../rendering-system/v2/diagram-renderer'
import { C4Edge, C4Node } from '../C4Diagram/C4Diagram'

export type C4BaseNodeProps = {
  diagramElementSpec: DiagramElementSpec
  renderElementsOptions?: RenderElementsOptions
}

export type C4BaseNode = {
  getUpdatedSpecs(
    rfInstance: ReactFlowInstance<C4Node, C4Edge>,
    node: NodeType,
  ): DiagramElementSpec | undefined
}

export function C4BaseNodeBuilder<T extends C4BaseNodeProps>(
  props: T,
  defaults?: DiagramElementSpec,
): C4BaseNode &
  Pick<NodeType<T>, 'id' | 'data' | 'position'> &
  Partial<NodeType<T>> {
  return {
    id: `${defaults?.alias ?? `c4BaseNode`}-${uuidV4()}`,
    data: props,
    position: {
      x:
        props.diagramElementSpec?.position?.left ??
        defaults?.position?.left ??
        0,
      y:
        props.diagramElementSpec?.position?.top ?? defaults?.position?.top ?? 0,
    },
    getUpdatedSpecs(
      rfInstance: ReactFlowInstance<C4Node, C4Edge>,
      node: C4Node,
    ): DiagramElementSpec | undefined {
      console.log(node.position)
      return node.data.diagramElementSpec
    },
  }
}
