import {
  Node as NodeType,
  NodeProps,
  NodeResizer,
  ReactFlowInstance,
} from '@xyflow/react'
import { ComponentType } from 'react'
import { v4 as uuidV4 } from 'uuid'

import { editableNode } from '../../../helper/react-flow-helper'
import { DiagramElementSpec } from '../../../models/autogenerated/DiagramElementSpec'
import { RenderElementsOptions } from '../../../rendering-system/v2/diagram-renderer'
import { C4Edge, C4Node } from '../C4DiagramCanvas/C4DiagramCanvas'

export type C4BaseNodeProps = {
  diagramElementSpec: DiagramElementSpec
  renderElementsOptions?: RenderElementsOptions
  resizable?: boolean
}

export type C4BaseNode = {
  getUpdatedSpecs(
    rfInstance: ReactFlowInstance<C4Node, C4Edge>,
    node: NodeType,
  ): DiagramElementSpec | undefined
}

export function C4BaseNodeBuilder<T extends C4BaseNodeProps>(
  props: T,
  defaults?: DiagramElementSpec,
): C4BaseNode &
  Pick<NodeType<T>, 'id' | 'data' | 'position'> &
  Partial<NodeType<T>> {
  let scaledWidth, scaledHeight
  if (props.diagramElementSpec.size?.width) {
    scaledWidth =
      props.diagramElementSpec.size.width *
      (props.diagramElementSpec.size.scale_x ?? 1)
  }
  if (props.diagramElementSpec.size?.height) {
    scaledHeight =
      props.diagramElementSpec.size.height *
      (props.diagramElementSpec.size.scale_y ?? 1)
  }

  return {
    id: defaults?.alias ?? `c4BaseNode-${uuidV4()}`,
    data: props,
    position: {
      x:
        props.diagramElementSpec?.position?.left ??
        defaults?.position?.left ??
        0,
      y:
        props.diagramElementSpec?.position?.top ?? defaults?.position?.top ?? 0,
    },
    width: scaledWidth,
    height: scaledHeight,
    ...editableNode(props.resizable),
    getUpdatedSpecs(
      rfInstance: ReactFlowInstance<C4Node, C4Edge>,
      node: C4Node,
    ): DiagramElementSpec | undefined {
      return node.data.diagramElementSpec
    },
  }
}

export function withC4BaseNode<
  T extends Record<string, unknown> & C4BaseNodeProps,
  K extends string,
>(
  Component: ComponentType<NodeProps<C4Node<T, K>>>,
): ComponentType<NodeProps<C4Node<T, K>>> {
  return function C4BaseNode(node: NodeProps<C4Node<T, K>>) {
    const resizable =
      node.data.resizable === undefined || node.data.resizable === true
    return (
      <>
        {resizable && (
          <NodeResizer
            color="#ff0071"
            isVisible={node.selected}
            keepAspectRatio={true}
          />
        )}
        <Component {...node} />
      </>
    )
  }
}
