import { Diagram, DiagramListener } from '@keadex/c4-model-ui-kit'
import {
  DiagramDesignView,
  DiagramDesignViewCommands,
} from '@keadex/keadex-mina/src/views/DiagramEditor/DiagramDesignView/DiagramDesignView'
import {
  ContextMenu,
  DropdownMenu,
  DropdownMenuItemProps,
  useAppBootstrap,
} from '@keadex/keadex-ui-kit/cross'
import { useEffect, useRef, useState } from 'react'
import {
  diagram_plantuml_url_from_diagram_url,
  diagram_spec_url_from_diagram_url,
  diagram_url_from_link_string,
  open_diagram,
  project_settings_url,
} from '../../../src-rust/pkg'
import { ProjectSettings } from '@keadex/keadex-mina/src/models/autogenerated/ProjectSettings'

export interface MinaReactProps {
  projectRootUrl: string
  diagramUrl: string
  ghToken?: string
}

export const MinaReact = (props: MinaReactProps) => {
  const { projectRootUrl, diagramUrl, ghToken } = props

  async function initializeTailwindElements() {
    const { initTE, Dropdown } = await import('tw-elements')
    await initTE({ Dropdown })
  }

  useAppBootstrap({ initTE: initializeTailwindElements })

  const diagramDesignViewRef = useRef<DiagramDesignViewCommands>(null)
  const [diagram, setDiagram] = useState<Diagram | null>()
  const [projectSettings, setProjectSettings] =
    useState<ProjectSettings | null>()
  const [error, setError] = useState<string | null>()

  const listener: DiagramListener = {
    onOpenDiagramClick: (link) => {
      let diagramUrl
      try {
        diagramUrl = diagram_url_from_link_string(projectRootUrl, link)
      } catch (e) {
        console.error(e)
        setErrorState(
          'Invalid URL: the provided URL is an invalid Mina project or diagram.',
        )
      }
      if (diagramUrl) openDiagram(diagramUrl)
    },
    onOpenExternalLinkClick: (externalLink: string) => {
      window.open(externalLink, '_blank')
    },
  }

  function setErrorState(error: string | null) {
    setDiagram(null)
    setError(error)
  }

  async function fetchGhRawFile(url: string, ghToken?: string) {
    // The following check is required to reduce the load on the Keadex backend.
    if (ghToken) {
      // Use the Keadex API as a proxy only when a GitHub token is configured.
      // In this case, in fact, you have to invoke the GitHub endpoint by passing
      // the token in the "Authorization" header, which is allowed only on server-side.
      const apiUrl = 'https://keadex.dev/api/download-gh-raw-file'
      const headers: {
        headers: { 'Keadex-Gh-Url': string; 'Keadex-Gh-Authorization'?: string }
      } = {
        headers: {
          'Keadex-Gh-Url': url,
        },
      }
      if (ghToken) {
        headers.headers['Keadex-Gh-Authorization'] = ghToken
      }
      return await fetch(apiUrl, headers)
    } else {
      return await fetch(url)
    }
  }

  async function openDiagram(url: string) {
    diagramDesignViewRef.current?.resetCanvas()
    let projectSettingsUrl
    let plantumlUrl
    let specUrl
    try {
      projectSettingsUrl = project_settings_url(projectRootUrl)
      plantumlUrl = diagram_plantuml_url_from_diagram_url(projectRootUrl, url)
      specUrl = diagram_spec_url_from_diagram_url(projectRootUrl, url)
    } catch (e) {
      console.error(e)
      setErrorState(
        'Invalid URL: the provided URL is an invalid Mina project or diagram.',
      )
    }

    if (projectSettingsUrl && plantumlUrl && specUrl) {
      let projectSettingsJson
      let plantuml
      let spec
      try {
        const projectSettingsResponse = await fetchGhRawFile(
          projectSettingsUrl,
          ghToken,
        )
        const plantumlResponse = await fetchGhRawFile(plantumlUrl, ghToken)
        const specResponse = await fetchGhRawFile(specUrl, ghToken)

        if (
          projectSettingsResponse.ok &&
          plantumlResponse.ok &&
          specResponse.ok
        ) {
          projectSettingsJson = await projectSettingsResponse.text()
          plantuml = await plantumlResponse.text()
          spec = await specResponse.text()
        } else {
          throw new Error()
        }
      } catch (e) {
        console.error(e)
        setErrorState(
          'Diagram or project settings not found. Please verify the URLs provided, or, if linking to a private repository, ensure the GitHub token is configured.',
        )
      }

      if (projectSettingsJson && plantuml && spec) {
        try {
          setProjectSettings(JSON.parse(projectSettingsJson) as ProjectSettings)
          setDiagram(
            open_diagram(projectRootUrl, url, plantuml, spec) as Diagram,
          )
        } catch (e) {
          setErrorState('Invalid diagram or project settings.')
        }
      }
    }
  }

  useEffect(() => {
    setErrorState(null)
    openDiagram(diagramUrl)
  }, [diagramUrl, projectRootUrl, ghToken])

  // Workaround to initialize TW Elements dropdown
  const menuItems: DropdownMenuItemProps[] = [
    {
      id: 'dropdown-init',
      label: '',
      isHeaderMenuItem: true,
      subMenuItems: [
        {
          id: `dropdown-init-1`,
          label: '',
        },
      ],
    },
  ]

  return (
    <div className="h-full w-full border-t flex items-center">
      <DropdownMenu menuItemsProps={menuItems} className="hidden" />
      <ContextMenu />
      {error === null && diagram && (
        <DiagramDesignView
          diagramListener={listener}
          diagram={diagram}
          ref={diagramDesignViewRef}
          diagramsThemeSettings={
            projectSettings?.themes_settings?.diagrams_theme_settings
          }
          target="web"
          readOnly
        />
      )}
      {error && <div className="w-full text-center text-black">{error}</div>}
    </div>
  )
}

export default MinaReact
