'use client'

import '@xyflow/react/dist/style.css'

import { debounce } from '@keadex/keadex-utils'
import {
  addEdge,
  applyEdgeChanges,
  applyNodeChanges,
  Background,
  BackgroundVariant,
  Connection,
  Edge as EdgeType,
  EdgeChange,
  MiniMap,
  Node as NodeType,
  NodeChange,
  OnEdgesChange,
  OnNodesChange,
  Panel,
  ReactFlow,
  ReactFlowInstance,
  useEdgesState,
  useNodesState,
} from '@xyflow/react'
import {
  ForwardedRef,
  forwardRef,
  MouseEvent,
  MouseEventHandler,
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from 'react'

import { readOnlyEdge, readOnlyNode } from '../../../helper/react-flow-helper'
import { DiagramElementSpec } from '../../../models/autogenerated/DiagramElementSpec'
import { DiagramOrientation } from '../../../models/autogenerated/DiagramOrientation'
import { DIAGRAM } from '../../../styles/style-constants'
import { DiagramListener } from '../../C4BaseComponent'
import { C4BaseNodeData } from '../C4BaseNode/C4BaseNode'
import {
  C4Legend,
  NODE_TYPE as C4_LEGEND_NODE_TYPE,
} from '../C4Legend/C4Legend'

const PAN_STEP = 50 // pixels, tune to taste

export type C4Node<
  T extends Record<string, unknown> & C4BaseNodeData = C4BaseNodeData,
  K extends string | undefined = undefined,
> = NodeType<T, K>
export type C4Edge = EdgeType & {}

const nodeTypes = {
  [C4_LEGEND_NODE_TYPE]: C4Legend,
}

export type C4DiagramCanvasState = {
  zoom: number
  pan: { x: number; y: number }
}

export type C4DiagramCanvasConfig = {
  autoLayoutEnabled: boolean
  autoLayoutOrientation?: DiagramOrientation
  backgroundColor: string
  gridEnabled: boolean
  zoom: number
  pan: { x: number; y: number }
  viewport: { x: number; y: number; zoom: number }
  readOnlyGlobalFlag?: boolean
  codingFeaturesEnabled: boolean
}

export type C4DiagramCanvasProps = {
  readOnly?: boolean
  codingFeaturesEnabled: boolean
  onDiagramModified?: () => void
  onMouseEnter?: (event?: MouseEvent) => void
  onMouseLeave?: (event?: MouseEvent) => void
}

export type C4DiagramCanvasCommands = {
  setDiagramListener: (diagramListener: DiagramListener) => void
  setAutoLayoutEnabled: (enabled: boolean) => void
  setAutoLayoutOrientation: (orientation?: DiagramOrientation) => void
  setBackgroundColor: (color: string) => void
  setGridEnabled: (enabled: boolean) => void
  setReadOnly: (readOnly: boolean) => void
  isReadOnly: () => boolean
  getAutoLayoutEnabled: () => boolean
  getAutoLayoutOrientation: () => DiagramOrientation | undefined
  setZoom: (zoom: number) => void
  getZoom: () => number
  setPan: (pan: { x: number; y: number }) => void
  getPan: () => { x: number; y: number }
  setNodes: (nodes: C4Node[]) => void
  setEdges: (edges: C4Edge[]) => void
  getUpdatedDiagramSpec: () => Array<DiagramElementSpec>
  panBy: (dx: number, dy: number) => void
  panLeft: () => void
  panRight: () => void
  panUp: () => void
  panDown: () => void
  resetPan: () => void
  resetZoom: () => void
  zoomIn: () => void
  zoomOut: () => void
  getCodingFeaturesEnabled: () => boolean
  setCodingFeaturesEnabled: (enabled: boolean) => void
}

export const C4DiagramCanvas = forwardRef(
  (props: C4DiagramCanvasProps, ref: ForwardedRef<C4DiagramCanvasCommands>) => {
    const {
      readOnly: readOnlyProp,
      codingFeaturesEnabled: codingFeaturesEnabledProp,
      onDiagramModified,
      onMouseEnter,
      onMouseLeave,
    } = props

    const debouncedModified = useMemo(
      () =>
        debounce(() => {
          if (onDiagramModified) onDiagramModified()
        }, 300),
      [onDiagramModified],
    )
    const [rfInstance, setRfInstance] = useState<ReactFlowInstance<
      C4Node,
      C4Edge
    > | null>(null)
    const [nodes, setNodes] = useNodesState<C4Node>([])
    const [edges, setEdges] = useEdgesState<C4Edge>([])
    const diagramListener = useRef<DiagramListener | null>(null)

    //---- Start configs
    const config = useRef<C4DiagramCanvasConfig>({
      autoLayoutEnabled: true,
      autoLayoutOrientation: 'TopToBottom',
      backgroundColor: DIAGRAM.COLOR.BG_COLOR,
      gridEnabled: false,
      zoom: 1,
      pan: { x: 0, y: 0 },
      viewport: { x: 0, y: 0, zoom: 1 },
      readOnlyGlobalFlag: readOnlyProp,
      codingFeaturesEnabled: codingFeaturesEnabledProp,
    })

    const [gridEnabled, _setGridEnabled] = useState(false)
    const [backgroundColor, _setBackgroundColor] = useState(
      DIAGRAM.COLOR.BG_COLOR,
    )
    const [zoom, _setZoom] = useState(1)
    const [pan, _setPan] = useState({ x: 0, y: 0 })
    const [viewport, _setViewport] = useState({ x: pan.x, y: pan.y, zoom })
    //---- End configs

    function setViewport(viewport: { x: number; y: number; zoom: number }) {
      _setViewport(viewport)
      config.current.viewport = viewport
    }

    //---- Start Ref implementation
    function setDiagramListener(newDiagramListener: DiagramListener) {
      diagramListener.current = newDiagramListener
    }

    function getAutoLayoutEnabled() {
      return config.current.autoLayoutEnabled
    }

    function getAutoLayoutOrientation() {
      return config.current.autoLayoutOrientation
    }

    function getZoom() {
      return config.current.viewport.zoom
    }

    function getPan() {
      return { x: config.current.viewport.x, y: config.current.viewport.y }
    }

    function getUpdatedDiagramSpec(): Array<DiagramElementSpec> {
      const newDiagramElementsSpecs = Array<DiagramElementSpec>()
      nodes.forEach((node) => {
        // Diagram element specs should be generated only it the diagram element
        // has been customized (custom position, size, etc.), otherwise the rendering
        // system will use the generated auto layout
        const updatedSpecs = node.data.getUpdatedSpecs(ref, node)
        if (updatedSpecs) {
          newDiagramElementsSpecs.push(updatedSpecs)
        }
      })

      return newDiagramElementsSpecs
    }

    function setReadOnlyGlobalFlag(readOnlyGlobalFlag: boolean) {
      config.current.readOnlyGlobalFlag = readOnlyGlobalFlag
    }

    function setReadOnly(readOnly: boolean) {
      setReadOnlyGlobalFlag(readOnly)
      setNodes((nds) => nds.map((node) => readOnlyNode(node, readOnly)))
      setEdges((eds) => eds.map((edge) => readOnlyEdge(edge, readOnly)))
    }

    function isReadOnly() {
      return config.current.readOnlyGlobalFlag ?? false
    }

    function setAutoLayoutEnabled(autoLayoutEnabled: boolean) {
      config.current.autoLayoutEnabled = autoLayoutEnabled
    }

    function setAutoLayoutOrientation(
      autoLayoutOrientation?: DiagramOrientation,
    ) {
      config.current.autoLayoutOrientation = autoLayoutOrientation
    }

    function setBackgroundColor(backgroundColor: string) {
      _setBackgroundColor(backgroundColor)
      config.current.backgroundColor = backgroundColor
    }

    function setGridEnabled(gridEnabled: boolean) {
      _setGridEnabled(gridEnabled)
      config.current.gridEnabled = gridEnabled
    }

    function setZoom(zoom: number) {
      _setZoom(zoom)
      config.current.zoom = zoom
    }

    function setPan(pan: { x: number; y: number }) {
      _setPan(pan)
      config.current.pan = pan
    }

    function panBy(dx: number, dy: number) {
      const { x, y, zoom } = config.current.viewport
      setViewport({ x: x + dx, y: y + dy, zoom })
    }

    function panLeft() {
      panBy(PAN_STEP, 0)
    }
    function panRight() {
      panBy(-PAN_STEP, 0)
    }
    function panUp() {
      panBy(0, PAN_STEP)
    }
    function panDown() {
      panBy(0, -PAN_STEP)
    }

    function resetPan() {
      const { zoom } = config.current.viewport
      setViewport({ x: 0, y: 0, zoom })
    }

    function resetZoom() {
      const { x, y } = config.current.viewport
      setViewport({ x, y, zoom: 1 })
    }

    function zoomIn() {
      rfInstance?.zoomIn()
    }

    function zoomOut() {
      rfInstance?.zoomOut()
    }

    function getCodingFeaturesEnabled() {
      return config.current.codingFeaturesEnabled
    }

    function setCodingFeaturesEnabled(enabled: boolean) {
      config.current.codingFeaturesEnabled = enabled
    }

    useImperativeHandle(ref, () => ({
      setDiagramListener,
      setAutoLayoutEnabled,
      setAutoLayoutOrientation,
      setBackgroundColor,
      setGridEnabled,
      setReadOnly,
      isReadOnly,
      setZoom,
      setPan,
      setNodes,
      setEdges,
      getAutoLayoutEnabled,
      getAutoLayoutOrientation,
      getZoom,
      getPan,
      getUpdatedDiagramSpec,
      panBy,
      panLeft,
      panRight,
      panUp,
      panDown,
      resetPan,
      resetZoom,
      zoomIn,
      zoomOut,
      getCodingFeaturesEnabled,
      setCodingFeaturesEnabled,
    }))
    //---- End Ref implementation

    useEffect(() => {
      setViewport({ x: pan.x, y: pan.y, zoom })
    }, [pan, zoom])

    useEffect(() => {
      return () => debouncedModified.cancel()
    }, [debouncedModified])

    useEffect(() => {
      setReadOnly(readOnlyProp ?? false)
    }, [readOnlyProp])

    useEffect(() => {
      setCodingFeaturesEnabled(codingFeaturesEnabledProp)
    }, [codingFeaturesEnabledProp])

    const onConnect = useCallback(
      (params: Connection) => setEdges((eds) => addEdge(params, eds)),
      [setEdges],
    )

    const isDiagramModified = useCallback(
      (
        changeType: 'nodes' | 'edges',
        changes: NodeChange<C4Node>[] | EdgeChange<C4Edge>[],
      ) => {
        let hasFinalChange = false
        if (changeType === 'nodes') {
          changes = changes as NodeChange<C4Node>[]
          hasFinalChange = changes.some((change) => {
            if (change.type === 'position') return change.dragging === false
            if (change.type === 'dimensions') return change.resizing === false
            // other change types (select, remove, add) don't have an in-progress phase
            return false
          })
        } else {
          changes = changes as EdgeChange<C4Edge>[]
          // TODO: check if there is a way to detect if an edge change is in progress or not. For now, we will assume that any edge change is a final change.
          hasFinalChange = true
        }
        return hasFinalChange
      },
      [],
    )

    const onNodesChange: OnNodesChange<C4Node> = useCallback(
      (changes) => {
        setNodes((nds) => applyNodeChanges(changes, nds))
        if (isDiagramModified('nodes', changes)) {
          debouncedModified()
        }
      },
      [setNodes, debouncedModified, isDiagramModified],
    )

    const onEdgesChange: OnEdgesChange<C4Edge> = useCallback(
      (changes) => {
        setEdges((eds) => applyEdgeChanges(changes, eds))
        if (isDiagramModified('edges', changes)) {
          debouncedModified()
        }
      },
      [setEdges, debouncedModified, isDiagramModified],
    )

    const handleOnMouseEnter: MouseEventHandler<HTMLDivElement> = useCallback(
      (e) => {
        if (onMouseEnter) {
          onMouseEnter(e)
        }
      },
      [onMouseEnter],
    )

    const handleOnMouseLeave: MouseEventHandler<HTMLDivElement> = useCallback(
      (e) => {
        if (onMouseLeave) {
          onMouseLeave(e)
        }
      },
      [onMouseLeave],
    )

    const onSave = useCallback(() => {
      if (rfInstance) {
        rfInstance.getNodes().forEach((node) => {
          const updatedSpecs = node.data.getUpdatedSpecs(ref, node)
        })
        const flow = rfInstance.toObject()
        console.log('Flow saved:', flow)
      }
    }, [rfInstance])

    function test() {
      getUpdatedDiagramSpec()
      setReadOnly(!isReadOnly())
    }

    // panActivationKeyCode={null} -> see https://github.com/xyflow/xyflow/discussions/5690
    return (
      <ReactFlow
        colorMode="light"
        nodes={nodes}
        edges={edges}
        nodeTypes={nodeTypes}
        onInit={(rfInstance) => setRfInstance(rfInstance)}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onConnect={onConnect}
        style={{ backgroundColor }}
        panActivationKeyCode={null}
        autoPanOnNodeDrag={false}
        onMouseEnter={handleOnMouseEnter}
        onMouseLeave={handleOnMouseLeave}
        viewport={viewport}
        onViewportChange={(viewport) => setViewport(viewport)}
        deleteKeyCode={null}
      >
        <MiniMap position="bottom-right" />
        {gridEnabled && <Background variant={BackgroundVariant.Dots} />}
        <Panel position="top-right">
          <button className="xy-theme__button" onClick={test}>
            test
          </button>
        </Panel>
      </ReactFlow>
    )
  },
)

export default C4DiagramCanvas
