'use client'

import '@xyflow/react/dist/style.css'

import { debounce } from '@keadex/keadex-utils'
import {
  addEdge,
  applyEdgeChanges,
  applyNodeChanges,
  Background,
  BackgroundVariant,
  Connection,
  Controls,
  Edge as EdgeType,
  EdgeChange,
  MiniMap,
  Node as NodeType,
  NodeChange,
  OnEdgesChange,
  OnNodesChange,
  Panel,
  ReactFlow,
  ReactFlowInstance,
  useEdgesState,
  useNodesState,
} from '@xyflow/react'
import {
  ForwardedRef,
  forwardRef,
  MouseEvent,
  MouseEventHandler,
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from 'react'

import { DiagramElementSpec } from '../../../models/autogenerated/DiagramElementSpec'
import { DiagramOrientation } from '../../../models/autogenerated/DiagramOrientation'
import { DIAGRAM } from '../../../styles/style-constants'
import { DiagramListener } from '../../C4BaseComponent'
import { C4BaseNodeData } from '../C4BaseNode/C4BaseNode'
import {
  C4Legend,
  NODE_TYPE as C4_LEGEND_NODE_TYPE,
} from '../C4Legend/C4Legend'

export type C4Node<
  T extends Record<string, unknown> & C4BaseNodeData = C4BaseNodeData,
  K extends string | undefined = undefined,
> = NodeType<T, K>
export type C4Edge = EdgeType & {}

const nodeTypes = {
  [C4_LEGEND_NODE_TYPE]: C4Legend,
}

export type C4DiagramCanvasState = {
  zoom: number
  pan: { x: number; y: number }
}

export type C4DiagramCanvasProps = {
  readOnly?: boolean
  codingFeaturesEnabled?: boolean
  onDiagramModified?: () => void
  onMouseDown?: (event?: MouseEvent) => void
  onMouseOut?: (event?: MouseEvent) => void
}

export type C4DiagramCanvasCommands = {
  setDiagramListener: (diagramListener: DiagramListener) => void
  setAutoLayoutEnabled: (enabled: boolean) => void
  setAutoLayoutOrientation: (orientation?: DiagramOrientation) => void
  setBackgroundColor: (color: string) => void
  setGridEnabled: (enabled: boolean) => void
  setReadOnly: (readOnly: boolean) => void
  getAutoLayoutEnabled: () => boolean
  getAutoLayoutOrientation: () => DiagramOrientation | undefined
  setZoom: (zoom: number) => void
  getZoom: () => number
  setPan: (pan: { x: number; y: number }) => void
  getPan: () => { x: number; y: number }
  setNodes: (nodes: C4Node[]) => void
  setEdges: (edges: C4Edge[]) => void
  getUpdatedDiagramSpec: () => Array<DiagramElementSpec>
}

export const C4DiagramCanvas = forwardRef(
  (props: C4DiagramCanvasProps, ref: ForwardedRef<C4DiagramCanvasCommands>) => {
    const {
      readOnly: readOnlyProps,
      codingFeaturesEnabled,
      onDiagramModified,
      onMouseDown,
      onMouseOut,
    } = props

    const debouncedModified = useMemo(
      () =>
        debounce(() => {
          if (onDiagramModified) onDiagramModified()
        }, 300),
      [onDiagramModified],
    )
    const [rfInstance, setRfInstance] = useState<ReactFlowInstance<
      C4Node,
      C4Edge
    > | null>(null)
    const [nodes, setNodes] = useNodesState<C4Node>([])
    const [edges, setEdges] = useEdgesState<C4Edge>([])
    const diagramListener = useRef<DiagramListener | null>(null)
    const [autoLayoutEnabled, setAutoLayoutEnabled] = useState(true)
    const [autoLayoutOrientation, setAutoLayoutOrientation] = useState<
      DiagramOrientation | undefined
    >('TopToBottom')
    const [backgroundColor, setBackgroundColor] = useState(
      DIAGRAM.COLOR.BG_COLOR,
    )
    const [gridEnabled, setGridEnabled] = useState(false)
    const [readOnly, setReadOnly] = useState(readOnlyProps)
    const [zoom, setZoom] = useState(1)
    const [pan, setPan] = useState({ x: 0, y: 0 })
    const [viewport, setViewport] = useState({ x: pan.x, y: pan.y, zoom })

    useEffect(() => {
      setViewport({ x: pan.x, y: pan.y, zoom })
    }, [pan, zoom])

    useEffect(() => {
      return () => debouncedModified.cancel()
    }, [debouncedModified])

    //---- Start Ref implementation
    function setDiagramListener(newDiagramListener: DiagramListener) {
      diagramListener.current = newDiagramListener
    }

    function getAutoLayoutEnabled() {
      return autoLayoutEnabled
    }

    function getAutoLayoutOrientation() {
      return autoLayoutOrientation
    }

    function getZoom() {
      return viewport.zoom
    }

    function getPan() {
      return { x: viewport.x, y: viewport.y }
    }

    function getUpdatedDiagramSpec(): Array<DiagramElementSpec> {
      const newDiagramElementsSpecs = Array<DiagramElementSpec>()
      nodes.forEach((node) => {
        // Diagram element specs should be generated only it the diagram element
        // has been customized (custom position, size, etc.), otherwise the rendering
        // system will use the generated auto layout
        const updatedSpecs = node.data.getUpdatedSpecs(ref, node)
        console.log(updatedSpecs)
        if (updatedSpecs) {
          newDiagramElementsSpecs.push(updatedSpecs)
        }
      })

      return newDiagramElementsSpecs
    }

    useImperativeHandle(ref, () => ({
      setDiagramListener,
      setAutoLayoutEnabled,
      setAutoLayoutOrientation,
      setBackgroundColor,
      setGridEnabled,
      setReadOnly,
      setZoom,
      setPan,
      setNodes,
      setEdges,
      getAutoLayoutEnabled,
      getAutoLayoutOrientation,
      getZoom,
      getPan,
      getUpdatedDiagramSpec,
    }))
    //---- End Ref implementation

    const onConnect = useCallback(
      (params: Connection) => setEdges((eds) => addEdge(params, eds)),
      [setEdges],
    )

    const isDiagramModified = useCallback(
      (
        changeType: 'nodes' | 'edges',
        changes: NodeChange<C4Node>[] | EdgeChange<C4Edge>[],
      ) => {
        let hasFinalChange = false
        if (changeType === 'nodes') {
          changes = changes as NodeChange<C4Node>[]
          hasFinalChange = changes.some((change) => {
            if (change.type === 'position') return change.dragging === false
            if (change.type === 'dimensions') return change.resizing === false
            // other change types (select, remove, add) don't have an in-progress phase
            return false
          })
        } else {
          changes = changes as EdgeChange<C4Edge>[]
          // TODO: check if there is a way to detect if an edge change is in progress or not. For now, we will assume that any edge change is a final change.
          hasFinalChange = true
        }
        return hasFinalChange
      },
      [],
    )

    const onNodesChange: OnNodesChange<C4Node> = useCallback(
      (changes) => {
        setNodes((nds) => applyNodeChanges(changes, nds))
        if (isDiagramModified('nodes', changes)) {
          debouncedModified()
        }
      },
      [setNodes, debouncedModified, isDiagramModified],
    )

    const onEdgesChange: OnEdgesChange<C4Edge> = useCallback(
      (changes) => {
        setEdges((eds) => applyEdgeChanges(changes, eds))
        if (isDiagramModified('edges', changes)) {
          debouncedModified()
        }
      },
      [setEdges, debouncedModified, isDiagramModified],
    )

    const handleOnMouseOut: MouseEventHandler<HTMLDivElement> = useCallback(
      (e) => {
        if (onMouseOut) {
          onMouseOut(e)
        }
      },
      [onMouseOut],
    )

    const handleOnMouseDown: MouseEventHandler<HTMLDivElement> = useCallback(
      (e) => {
        if (onMouseDown) {
          onMouseDown(e)
        }
      },
      [onMouseDown],
    )

    const onSave = useCallback(() => {
      if (rfInstance) {
        rfInstance.getNodes().forEach((node) => {
          const updatedSpecs = node.data.getUpdatedSpecs(ref, node)
        })
        const flow = rfInstance.toObject()
        console.log('Flow saved:', flow)
      }
    }, [rfInstance])

    // panActivationKeyCode={null} -> see https://github.com/xyflow/xyflow/discussions/5690
    return (
      <ReactFlow
        colorMode="light"
        nodes={nodes}
        edges={edges}
        nodeTypes={nodeTypes}
        onInit={(rfInstance) => setRfInstance(rfInstance)}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onConnect={onConnect}
        style={{ backgroundColor }}
        panActivationKeyCode={null}
        autoPanOnNodeDrag={false}
        onMouseOut={handleOnMouseOut}
        onMouseDownCapture={handleOnMouseDown}
        viewport={viewport}
        onViewportChange={(viewport) => setViewport(viewport)}
      >
        <MiniMap />
        <Controls />
        <Background variant={BackgroundVariant.Dots} />
        <Panel position="top-right">
          <button className="xy-theme__button" onClick={getUpdatedDiagramSpec}>
            save
          </button>
        </Panel>
      </ReactFlow>
    )
  },
)

export default C4DiagramCanvas
