import {
  CONTAINER_TYPES,
  Container,
  ContainerType,
} from '@keadex/c4-model-ui-kit'
import {
  Input,
  Select,
  Textarea,
  renderButtons,
} from '@keadex/keadex-ui-kit/cross'
import { capitalCase, noCase } from 'change-case'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { toast } from 'react-toastify'
import { v4 as uuidv4 } from 'uuid'
import { ALIAS_REGEX, NAME_REGEX } from '../../../constants/regex'
import { useAppDispatch } from '../../../core/store/hooks'
import { saveProject } from '../../../core/store/slices/project-slice'
import {
  createLibraryElement,
  updateLibraryElement,
} from '../../../core/tauri-rust-bridge'
import { MinaError } from '../../../models/autogenerated/MinaError'
import { Project } from '../../../models/autogenerated/Project'
import DiagramLinker from '../../DiagramLinker/DiagramLinker'
import {
  ModalCRULibraryElementProps,
  normalizeLibraryElement,
} from '../ModalCRULibraryElements'

const emptyContainer: Container = {
  base_data: {
    uuid: uuidv4(),
    alias: '',
    label: '',
    description: '',
    notes: '',
  },
  technology: '',
}

export const ModalCRUContainer = (props: ModalCRULibraryElementProps) => {
  const { t } = useTranslation()
  const dispatch = useAppDispatch()
  const [newContainer, setNewContainer] = useState(
    props.libraryElement ? (props.libraryElement as Container) : emptyContainer,
  )
  const [isLoading, setIsLoading] = useState(false)

  function handleUpdateContainer() {
    setIsLoading(true)
    updateLibraryElement(
      { Container: props.libraryElement as Container },
      { Container: normalizeLibraryElement(newContainer) },
    )
      .then((updatedProjectLibrary) => {
        setIsLoading(false)
        if (props.project?.project_settings && props.project?.project_library) {
          const newProject: Project = {
            ...props.project,
            project_library: updatedProjectLibrary,
          }
          dispatch(saveProject(newProject))
          toast.info(t('common.info.done'))
          if (props.forceUpdate) props.forceUpdate()
          props.hideModal()
        }
      })
      .catch((error: MinaError) => {
        setIsLoading(false)
        toast.error(error.msg ?? error)
      })
  }

  function handleCreateContainer() {
    setIsLoading(true)
    createLibraryElement({ Container: normalizeLibraryElement(newContainer) })
      .then((updatedProjectLibrary) => {
        setIsLoading(false)
        if (props.project?.project_settings && props.project?.project_library) {
          const newProject: Project = {
            ...props.project,
            project_library: updatedProjectLibrary,
          }
          dispatch(saveProject(newProject))
          toast.info(t('common.info.done'))
          if (props.forceUpdate) props.forceUpdate()
          props.hideModal()
        }
      })
      .catch((error: MinaError) => {
        setIsLoading(false)
        toast.error(error.msg ?? error)
      })
  }

  function missingRequiredFields() {
    return (
      !newContainer?.base_data?.alias ||
      !newContainer?.base_data?.label ||
      !newContainer.container_type ||
      !newContainer.technology
    )
  }

  useEffect(() => {
    emptyContainer.base_data.uuid = uuidv4()
  }, [])

  return (
    <div>
      {/* Modal body */}
      <div className="modal__body">
        <Input
          disabled={true}
          type="text"
          label={`UUID`}
          className="mt-2"
          value={newContainer?.base_data?.uuid}
        />
        <Input
          disabled={props.libraryElement !== undefined || !props.enableEdit}
          type="text"
          label={`${t('common.alias')}*`}
          className="mt-6"
          allowedChars={ALIAS_REGEX}
          info={`${t('common.allowed_pattern')}: ${ALIAS_REGEX}`}
          value={newContainer?.base_data?.alias}
          onChange={(e) =>
            setNewContainer({
              ...newContainer,
              base_data: {
                ...newContainer?.base_data,
                alias: e.target.value.replace(' ', ''),
              },
            })
          }
        />
        <Input
          disabled={!props.enableEdit}
          type="text"
          label={`${t('common.label')}*`}
          className="mt-6"
          allowedChars={NAME_REGEX}
          info={`${t('common.allowed_pattern')}: ${NAME_REGEX}`}
          value={newContainer?.base_data?.label}
          onChange={(e) =>
            setNewContainer({
              ...newContainer,
              base_data: {
                ...newContainer?.base_data,
                label: e.target.value,
              },
            })
          }
        />
        <Select
          id="type-selector"
          disabled={!props.enableEdit}
          label={`${t('common.type')}*`}
          className="mt-6"
          value={newContainer?.container_type}
          options={[{ label: '', value: '' }].concat([
            ...new Set(
              CONTAINER_TYPES.map((containerType) => {
                return {
                  label: capitalCase(noCase(containerType)),
                  value: containerType,
                }
              }),
            ),
          ])}
          onChange={(e) =>
            setNewContainer({
              ...newContainer,
              container_type: e.target.value as ContainerType,
            })
          }
        />
        <Input
          disabled={!props.enableEdit}
          type="text"
          label={`${t('common.technology')}*`}
          className="mt-6"
          allowedChars={NAME_REGEX}
          info={`${t('common.allowed_pattern')}: ${NAME_REGEX}`}
          value={newContainer?.technology}
          onChange={(e) =>
            setNewContainer({
              ...newContainer,
              technology: e.target.value,
            })
          }
        />
        <Textarea
          id="container-description"
          disabled={!props.enableEdit}
          label={t('common.description')}
          className="mt-6"
          value={newContainer?.base_data?.description}
          onChange={(e) =>
            setNewContainer({
              ...newContainer,
              base_data: {
                ...newContainer?.base_data,
                description: e.target.value,
              },
            })
          }
        />
        <DiagramLinker
          hideButtons
          className="p-0"
          disabled={!props.enableEdit}
          link={newContainer?.base_data?.link}
          onLinkChanged={(link) => {
            setNewContainer({
              ...newContainer,
              base_data: {
                ...newContainer?.base_data,
                link,
              },
            })
          }}
        />
        {props.mode !== 'serializer' && (
          <Textarea
            id="container-note"
            disabled={!props.enableEdit}
            label={`${t('common.notes')}`}
            className="mt-6"
            value={newContainer?.base_data?.notes}
            onChange={(e) =>
              setNewContainer({
                ...newContainer,
                base_data: {
                  ...newContainer?.base_data,
                  notes: e.target.value,
                },
              })
            }
          />
        )}
        <span
          className={`text-sm text-orange-500 mt-2 ${
            missingRequiredFields() ? 'block' : 'hidden'
          }`}
        >
          * {t('common.info.fill_required_fields')}
        </span>
      </div>

      {/* Modal footer */}
      <div className="modal__footer">
        {renderButtons([
          {
            key: 'button-cancel',
            disabled: isLoading,
            children: <span>{t('common.cancel')}</span>,
            'data-te-modal-dismiss': true,
          },
          {
            key: 'button-save',
            children: <span>{t('common.save')}</span>,
            disabled: missingRequiredFields(),
            isLoading,
            onClick: () => {
              if (props.mode === 'serializer') {
                if (props.onElementCreated) {
                  props.onElementCreated({
                    Container: normalizeLibraryElement(newContainer),
                  })
                  props.hideModal()
                }
              } else if (props.project) {
                if (
                  props.libraryElement &&
                  props.mode !== 'createLibraryElement'
                ) {
                  handleUpdateContainer()
                } else {
                  handleCreateContainer()
                }
              }
            },
          },
        ])}
      </div>
    </div>
  )
}

export default ModalCRUContainer
