import { Graphviz } from '@hpcc-js/wasm-graphviz'
import { type JSX } from 'react'
import { toast } from 'react-toastify'
import { render as takumiRender } from 'takumi-js'
import { googleFonts } from 'takumi-js/helpers'

import { DiagramListener } from '../../components/C4BaseComponent'
import { C4BaseNodePropsSSRBuilder } from '../../components/v2/C4BaseNode/C4BaseNode'
import {
  C4DiagramCanvasCommands,
  C4Edge,
  C4Node,
} from '../../components/v2/C4DiagramCanvas/C4DiagramCanvas'
import {
  ALIAS as LEGEND_ALIAS,
  C4Legend,
  C4LegendNodeBuilder,
} from '../../components/v2/C4Legend/C4Legend'
import {
  ERROR_GRAPHVIZ_NOT_INITIALIZED,
  WARN_TOO_MANY_ELEMENTS,
} from '../../constants/errors'
import { ERROR_TRIANGULATION_FAILED } from '../../constants/errors'
import { getElementSpecByAlias } from '../../helper/diagram-helper'
import { AddElementTag } from '../../models/autogenerated/AddElementTag'
import { Diagram } from '../../models/autogenerated/Diagram'
import { DiagramElementType } from '../../models/autogenerated/DiagramElementType'
import { DiagramSpec } from '../../models/autogenerated/DiagramSpec'
import { DiagramsThemeSettings } from '../../models/autogenerated/DiagramsThemeSettings'
import { ElementData } from '../../models/autogenerated/ElementData'
import stylesheet from '../../styles/index.css?inline'
import { DIAGRAM } from '../../styles/style-constants'
import { generateAutoLayout } from '../auto-layout'

export type DiagramRendererOutput = {
  nodes: C4Node[]
  edges: C4Edge[]
  components: JSX.Element[]
  render?: JSX.Element
}

export class DiagramRenderer {
  graphviz?: Graphviz

  async initialize(): Promise<DiagramRenderer> {
    this.graphviz = await Graphviz.load()
    return this
  }

  renderDiagram(
    c4DiagramRef: C4DiagramCanvasCommands | null,
    diagramListener: DiagramListener,
    diagram: Diagram | undefined,
    diagramsThemeSettings: DiagramsThemeSettings | undefined,
    ssr = false,
  ): DiagramRendererOutput {
    let result: DiagramRendererOutput = { nodes: [], edges: [], components: [] }
    if (diagram) {
      c4DiagramRef?.setDiagramListener(diagramListener)
      c4DiagramRef?.setAutoLayoutEnabled(
        !!diagram.diagram_spec?.auto_layout_enabled,
      )
      c4DiagramRef?.setGridEnabled(!!diagram.diagram_spec?.grid_enabled)
      c4DiagramRef?.setAutoLayoutOrientation(
        diagram.diagram_spec?.auto_layout_orientation,
      )
      c4DiagramRef?.setBackgroundColor(
        diagramsThemeSettings?.bg_color_diagram ?? DIAGRAM.COLOR.BG_COLOR,
      )

      if (diagram.diagram_spec?.auto_layout_enabled) {
        if (this.graphviz) {
          const autoLayout = generateAutoLayout(this.graphviz, diagram)
          diagram.auto_layout = autoLayout.positions
          diagram.auto_layout_errors = autoLayout.errors
          if (autoLayout.errors.length > 0) {
            if (autoLayout.errors.indexOf(ERROR_TRIANGULATION_FAILED) >= 0) {
              console.warn(WARN_TOO_MANY_ELEMENTS)
              toast.warn(WARN_TOO_MANY_ELEMENTS)
            } else {
              console.error(autoLayout.errors.join(', '))
              toast.error(autoLayout.errors.join(', '))
            }
          }
        } else {
          console.error(ERROR_GRAPHVIZ_NOT_INITIALIZED)
          toast.error(ERROR_GRAPHVIZ_NOT_INITIALIZED)
        }
      }

      result = renderElements(
        c4DiagramRef,
        diagram.diagram_plantuml?.elements,
        diagram.diagram_spec,
        diagram.auto_layout ?? {},
        {
          diagramsThemeSettings,
          tags: diagram.diagram_plantuml?.tags,
          ssr,
        },
      )
      // restoreZIndex(components)
    }

    if (ssr) {
      result.render = (
        <div
          style={{
            display: 'flex',
            background: '#f6f6f6',
            width: '100%',
            height: '100%',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          {result.components}
        </div>
      )
    }
    return result
  }

  async exportDiagramSSR(
    diagramListener: DiagramListener,
    diagram: Diagram,
    diagramsThemeSettings: DiagramsThemeSettings | undefined,
    format: 'jpeg' | 'png' = 'png',
  ) {
    function toDataUrl(bytes: Uint8Array, format: 'jpeg' | 'png'): string {
      const mimeMap = {
        jpeg: 'image/jpeg',
        png: 'image/png',
      }
      let binary = ''
      bytes.forEach((byte) => {
        binary += String.fromCharCode(byte)
      })
      return `data:${mimeMap[format]};base64,${btoa(binary)}`
    }

    // Render the diagram server side
    const ssr = this.renderDiagram(
      null,
      diagramListener,
      diagram,
      diagramsThemeSettings,
      true,
    )

    // Export the diagram server side
    const img = await takumiRender(ssr.render, {
      width: 1200,
      height: 630,
      fonts: googleFonts([{ name: 'Roboto', weight: 400 }]),
      stylesheets: [stylesheet],
      format: format as 'png', // casting is a workaround to avoid type error
    })

    return toDataUrl(img, format)
  }
}
export type RenderElementsOptions = {
  skipLegendRendering?: boolean
  skipAddToCanvas?: boolean
  diagramsThemeSettings?: DiagramsThemeSettings | undefined
  tags?: Record<string, AddElementTag>
  ssr?: boolean
}

export const renderElements = (
  c4DiagramRef: C4DiagramCanvasCommands | null,
  diagramElements: DiagramElementType[] | undefined,
  diagramSpec: DiagramSpec | undefined,
  autoLayout: Record<string, ElementData>,
  options?: RenderElementsOptions,
): DiagramRendererOutput => {
  const nodes: C4Node[] = []
  const edges: C4Edge[] = []
  const components: JSX.Element[] = []

  if (diagramSpec) {
    if (!options || !options.skipLegendRendering) {
      const node = C4LegendNodeBuilder({
        diagramElementSpec: getElementSpecByAlias(
          LEGEND_ALIAS,
          undefined,
          undefined,
          undefined,
          diagramSpec,
        ),
        renderElementsOptions: options,
      })
      nodes.push(node)
      if (options?.ssr) {
        components.push(<C4Legend {...C4BaseNodePropsSSRBuilder(node)} />)
      }
    }
  }

  c4DiagramRef?.setNodes(nodes)
  c4DiagramRef?.setEdges(edges)
  return { nodes, edges, components }
}
// export const renderElements = (
//   canvas: KeadexCanvas | undefined,
//   diagramElements: DiagramElementType[] | undefined,
//   diagramSpec: DiagramSpec | undefined,
//   autoLayout: Record<string, ElementData>,
//   options?: RenderElementsOptions,
// ): C4BaseComponent[] => {
//   const components: C4BaseComponent[] = []
//   if (diagramSpec) {
//     if (!options || !options.skipLegendRendering) {
//       const component = C4Legend(
//         getElementSpecByAlias(
//           LEGEND_ALIAS,
//           undefined,
//           undefined,
//           undefined,
//           diagramSpec,
//         ),
//         options,
//       )
//       if (component) {
//         components.push(component)
//         canvas?.add(component)
//       }
//     }
//     if (diagramElements) {
//       for (const element of diagramElements) {
//         if (boundaryDiagramElement(element)) {
//           const component = renderBoundaryDiagramElement(
//             canvas,
//             boundaryDiagramElement(element) as Boundary,
//             diagramSpec,
//             autoLayout,
//             options,
//           )
//           if (component) components.push(component)
//         } else if (componentDiagramElement(element)) {
//           const component = renderComponentDiagramElement(
//             canvas,
//             componentDiagramElement(element) as Component,
//             diagramSpec,
//             autoLayout,
//             options,
//           )
//           if (component) components.push(component)
//         } else if (containerDiagramElement(element)) {
//           const component = renderContainerDiagramElement(
//             canvas,
//             containerDiagramElement(element) as Container,
//             diagramSpec,
//             autoLayout,
//             options,
//           )
//           if (component) components.push(component)
//         } else if (deploymentNodeDiagramElement(element)) {
//           const component = renderDeploymentNodeDiagramElement(
//             canvas,
//             deploymentNodeDiagramElement(element) as DeploymentNode,
//             diagramSpec,
//             autoLayout,
//             options,
//           )
//           if (component) components.push(component)
//         } else if (personDiagramElement(element)) {
//           const component = renderPersonDiagramElement(
//             canvas,
//             personDiagramElement(element) as Person,
//             diagramSpec,
//             autoLayout,
//             options,
//           )
//           if (component) components.push(component)
//         } else if (relationshipDiagramElement(element)) {
//           const component = renderRelationshipDiagramElement(
//             canvas,
//             relationshipDiagramElement(element) as Relationship,
//             diagramSpec,
//             autoLayout,
//             options,
//           )
//           if (component) components.push(component)
//         } else if (softwareSystemDiagramElement(element)) {
//           const component = renderSoftwareSystemDiagramElement(
//             canvas,
//             softwareSystemDiagramElement(element) as SoftwareSystem,
//             diagramSpec,
//             autoLayout,
//             options,
//           )
//           if (component) components.push(component)
//         }
//       }
//     }
//   }
//   return components
// }

// /**
//  * During the rendering process, it will be used the default z-index generated by Fabric.js.
//  * Since the user might change the z-index from the Design View, this function is used
//  * to restore the z-index eventually changed and saved by the user.
//  *
//  * IMPORTANT: This function must be executed only after all the objects are rendered
//  * since the saved z-index is relative to all the objects on the canvas.
//  *
//  * @param components Fabric.js object to update
//  */
// const restoreZIndex = (components: fabric.Object[], parentZIndex?: number) => {
//   components.forEach((component) => {
//     let zIndex = getSavedZIndex(component)
//     // console.debug(
//     //   `Name:${
//     //     component.name
//     //   }\nParent zindex:${parentZIndex}\nSaved Zindex:${zIndex}\nCanvas zindex:${getZIndexOfObject(
//     //     component.canvas,
//     //     component,
//     //   )}\nChildren: ${component.children?.length}`,
//     // )
//     if (zIndex) {
//       if (parentZIndex && zIndex <= parentZIndex) {
//         zIndex = parentZIndex + 1
//         parentZIndex++
//         // console.debug(`New zindex ${zIndex}`)
//       }
//       component.moveTo(zIndex)
//     }

//     if (component.isVirtualGroupParent()) {
//       // In case of virtual groups, we must pass also the parent z-index since it will be used
//       // to evetually fix the children z-indexes. If the parent z-index has not been saved,
//       // we use the current z-index (genereated by Fabric.js) of the first children,
//       // which is the base shape of the object (e.g. the rectangle in C4BaseElasticContainer)
//       restoreZIndex(
//         component.children!,
//         zIndex ?? getZIndexOfObject(component.canvas, component.children![0]),
//       )
//     }
//   })
// }
