import { Graphviz } from '@hpcc-js/wasm-graphviz'
import { toast } from 'react-toastify'

import {
  C4BaseComponent,
  DiagramListener,
} from '../../components/C4BaseComponent'
import {
  C4DiagramCommmands,
  C4DiagramEdge,
  C4DiagramNode,
} from '../../components/v2/C4Diagram/C4Diagram'
import {
  ERROR_GRAPHVIZ_NOT_INITIALIZED,
  WARN_TOO_MANY_ELEMENTS,
} from '../../constants/errors'
import { ERROR_TRIANGULATION_FAILED } from '../../constants/errors'
import { AddElementTag } from '../../models/autogenerated/AddElementTag'
import { Diagram } from '../../models/autogenerated/Diagram'
import { DiagramElementType } from '../../models/autogenerated/DiagramElementType'
import { DiagramSpec } from '../../models/autogenerated/DiagramSpec'
import { DiagramsThemeSettings } from '../../models/autogenerated/DiagramsThemeSettings'
import { ElementData } from '../../models/autogenerated/ElementData'
import { DIAGRAM } from '../../styles/style-constants'
import { generateAutoLayout } from '../auto-layout'

export class DiagramRenderer {
  graphviz?: Graphviz

  async initialize(): Promise<DiagramRenderer> {
    this.graphviz = await Graphviz.load()
    return this
  }

  renderDiagram(
    c4DiagramRef: C4DiagramCommmands | null,
    diagramListener: DiagramListener,
    diagram: Diagram | undefined,
    diagramsThemeSettings: DiagramsThemeSettings | undefined,
  ): C4BaseComponent[] | undefined {
    if (c4DiagramRef && diagram) {
      c4DiagramRef.setDiagramListener(diagramListener)
      c4DiagramRef.setAutoLayoutEnabled(
        !!diagram.diagram_spec?.auto_layout_enabled,
      )
      c4DiagramRef.setAutoLayoutOrientation(
        diagram.diagram_spec?.auto_layout_orientation,
      )
      c4DiagramRef.setBackgroundColor(
        diagramsThemeSettings?.bg_color_diagram ?? DIAGRAM.COLOR.BG_COLOR,
      )

      if (diagram.diagram_spec?.auto_layout_enabled) {
        if (this.graphviz) {
          const autoLayout = generateAutoLayout(this.graphviz, diagram)
          diagram.auto_layout = autoLayout.positions
          diagram.auto_layout_errors = autoLayout.errors
          if (autoLayout.errors.length > 0) {
            if (autoLayout.errors.indexOf(ERROR_TRIANGULATION_FAILED) >= 0) {
              console.warn(WARN_TOO_MANY_ELEMENTS)
              toast.warn(WARN_TOO_MANY_ELEMENTS)
            } else {
              console.error(autoLayout.errors.join(', '))
              toast.error(autoLayout.errors.join(', '))
            }
          }
        } else {
          console.error(ERROR_GRAPHVIZ_NOT_INITIALIZED)
          toast.error(ERROR_GRAPHVIZ_NOT_INITIALIZED)
        }
      }

      c4DiagramRef.setGridEnabled(!!diagram.diagram_spec?.grid_enabled)

      const components = renderElements(
        c4DiagramRef,
        diagram.diagram_plantuml?.elements,
        diagram.diagram_spec,
        diagram.auto_layout ?? {},
        {
          diagramsThemeSettings,
          tags: diagram.diagram_plantuml?.tags,
        },
      )
      // restoreZIndex(components)
      return components
    }
    return
  }
}
export type RenderElementsOptions = {
  skipLegendRendering?: boolean
  skipAddToCanvas?: boolean
  diagramsThemeSettings?: DiagramsThemeSettings | undefined
  tags?: Record<string, AddElementTag>
}

export const renderElements = (
  c4DiagramRef: C4DiagramCommmands | null,
  diagramElements: DiagramElementType[] | undefined,
  diagramSpec: DiagramSpec | undefined,
  autoLayout: Record<string, ElementData>,
  options?: RenderElementsOptions,
): C4BaseComponent[] => {
  const components: C4BaseComponent[] = []
  const nodes: C4DiagramNode[] = []
  const edges: C4DiagramEdge[] = []

  console.log('renderiiiiing')
  console.log(c4DiagramRef)
  const initialNodes = [
    { id: '1', position: { x: 0, y: 0 }, data: { label: '1' } },
    { id: '2', position: { x: 0, y: 100 }, data: { label: '2' } },
  ]
  const initialEdges = [{ id: 'e1-2', source: '1', target: '2' }]
  c4DiagramRef?.setNodes(initialNodes)
  c4DiagramRef?.setEdges(initialEdges)

  return components
}
// export const renderElements = (
//   canvas: KeadexCanvas | undefined,
//   diagramElements: DiagramElementType[] | undefined,
//   diagramSpec: DiagramSpec | undefined,
//   autoLayout: Record<string, ElementData>,
//   options?: RenderElementsOptions,
// ): C4BaseComponent[] => {
//   const components: C4BaseComponent[] = []
//   if (diagramSpec) {
//     if (!options || !options.skipLegendRendering) {
//       const component = C4Legend(
//         getElementSpecByAlias(
//           LEGEND_ALIAS,
//           undefined,
//           undefined,
//           undefined,
//           diagramSpec,
//         ),
//         options,
//       )
//       if (component) {
//         components.push(component)
//         canvas?.add(component)
//       }
//     }
//     if (diagramElements) {
//       for (const element of diagramElements) {
//         if (boundaryDiagramElement(element)) {
//           const component = renderBoundaryDiagramElement(
//             canvas,
//             boundaryDiagramElement(element) as Boundary,
//             diagramSpec,
//             autoLayout,
//             options,
//           )
//           if (component) components.push(component)
//         } else if (componentDiagramElement(element)) {
//           const component = renderComponentDiagramElement(
//             canvas,
//             componentDiagramElement(element) as Component,
//             diagramSpec,
//             autoLayout,
//             options,
//           )
//           if (component) components.push(component)
//         } else if (containerDiagramElement(element)) {
//           const component = renderContainerDiagramElement(
//             canvas,
//             containerDiagramElement(element) as Container,
//             diagramSpec,
//             autoLayout,
//             options,
//           )
//           if (component) components.push(component)
//         } else if (deploymentNodeDiagramElement(element)) {
//           const component = renderDeploymentNodeDiagramElement(
//             canvas,
//             deploymentNodeDiagramElement(element) as DeploymentNode,
//             diagramSpec,
//             autoLayout,
//             options,
//           )
//           if (component) components.push(component)
//         } else if (personDiagramElement(element)) {
//           const component = renderPersonDiagramElement(
//             canvas,
//             personDiagramElement(element) as Person,
//             diagramSpec,
//             autoLayout,
//             options,
//           )
//           if (component) components.push(component)
//         } else if (relationshipDiagramElement(element)) {
//           const component = renderRelationshipDiagramElement(
//             canvas,
//             relationshipDiagramElement(element) as Relationship,
//             diagramSpec,
//             autoLayout,
//             options,
//           )
//           if (component) components.push(component)
//         } else if (softwareSystemDiagramElement(element)) {
//           const component = renderSoftwareSystemDiagramElement(
//             canvas,
//             softwareSystemDiagramElement(element) as SoftwareSystem,
//             diagramSpec,
//             autoLayout,
//             options,
//           )
//           if (component) components.push(component)
//         }
//       }
//     }
//   }
//   return components
// }

// /**
//  * During the rendering process, it will be used the default z-index generated by Fabric.js.
//  * Since the user might change the z-index from the Design View, this function is used
//  * to restore the z-index eventually changed and saved by the user.
//  *
//  * IMPORTANT: This function must be executed only after all the objects are rendered
//  * since the saved z-index is relative to all the objects on the canvas.
//  *
//  * @param components Fabric.js object to update
//  */
// const restoreZIndex = (components: fabric.Object[], parentZIndex?: number) => {
//   components.forEach((component) => {
//     let zIndex = getSavedZIndex(component)
//     // console.debug(
//     //   `Name:${
//     //     component.name
//     //   }\nParent zindex:${parentZIndex}\nSaved Zindex:${zIndex}\nCanvas zindex:${getZIndexOfObject(
//     //     component.canvas,
//     //     component,
//     //   )}\nChildren: ${component.children?.length}`,
//     // )
//     if (zIndex) {
//       if (parentZIndex && zIndex <= parentZIndex) {
//         zIndex = parentZIndex + 1
//         parentZIndex++
//         // console.debug(`New zindex ${zIndex}`)
//       }
//       component.moveTo(zIndex)
//     }

//     if (component.isVirtualGroupParent()) {
//       // In case of virtual groups, we must pass also the parent z-index since it will be used
//       // to evetually fix the children z-indexes. If the parent z-index has not been saved,
//       // we use the current z-index (genereated by Fabric.js) of the first children,
//       // which is the base shape of the object (e.g. the rectangle in C4BaseElasticContainer)
//       restoreZIndex(
//         component.children!,
//         zIndex ?? getZIndexOfObject(component.canvas, component.children![0]),
//       )
//     }
//   })
// }
