import './styles/index.css'

// Constants
export {
  ADD_ELEMENT_TAG_TYPES,
  AUTO_LAYOUT_ORIENTATIONS,
  BOUNDARY_TYPES,
  C4_ELEMENTS_TYPES,
  COMPONENT_TYPES,
  CONTAINER_TYPES,
  DEPLOYMENT_NODE_TYPES,
  DIAGRAM_ELEMENTS_TYPES,
  DIAGRAM_TYPES,
  PERSON_TYPES,
  RELATIONSHIP_TYPES,
  SYSTEM_TYPES,
} from './constants/diagram'
export {
  DIAGRAM_EXTERNAL_LINK_PROTOCOLS,
  DIAGRAM_INTERNAL_LINK_PROTOCOLS,
  DIAGRAM_LINKS_SEPARATOR,
  DiagramExternalLinkVariables,
} from './constants/diagram-link'
export {
  CANVAS_EVENTS,
  MOUSE_EVENTS,
  OBJECT_EVENTS,
} from './constants/fabric-events'
export {
  DEFAULT_GRAPHVIZ_SUBGRAPH_PAD,
  DEFAULT_SUBGRAPH_FAKE_FONT_SIZE,
  DEFAULT_SUBGRAPH_INNER_MARGIN,
  DEFAULT_SUBGRAPH_OUTER_MARGIN,
  GRAPHVIZ_DPI,
  PENWIDTH,
  PERIPHERIES,
  PERIPHERY_SIZE,
  X_PAD,
  Y_PAD,
} from './rendering-system/auto-layout/dot-serializer'
export {
  BOX,
  DIAGRAM,
  ELEMENT,
  LEGEND,
  RELATIONSHIP,
} from './styles/style-constants'

// Rendering System
export { generateAutoLayout } from './rendering-system/auto-layout/index'
export { renderBoundaryDiagramElement } from './rendering-system/boundary-renderer'
export { renderComponentDiagramElement } from './rendering-system/component-renderer'
export { renderContainerDiagramElement } from './rendering-system/container-renderer'
export { renderDeploymentNodeDiagramElement } from './rendering-system/deployment-node-renderer'
export { DiagramRenderer } from './rendering-system/diagram-renderer'
export { renderPersonDiagramElement } from './rendering-system/person-renderer'
export { renderRelationshipDiagramElement } from './rendering-system/relationship-renderer'
export { renderSoftwareSystemDiagramElement } from './rendering-system/software-system-renderer'
export { DiagramRenderer as DiagramRendererV2 } from './rendering-system/v2/diagram-renderer'

// Components
export { C4Component } from './components/c4-component/C4Component'
export { C4ComponentExt } from './components/c4-component/C4ComponentExt'
export { C4SoftwareSystem } from './components/c4-software-system/C4SoftwareSystem'
export { C4SoftwareSystemExt } from './components/c4-software-system/C4SoftwareSystemExt'
export { type DiagramListener } from './components/C4BaseComponent'
export { C4Legend } from './components/C4Legend'
export {
  C4Diagram,
  type C4DiagramCommmands,
} from './components/v2/C4Diagram/C4Diagram'

// Helpers
export {
  boundaryDiagramElement,
  c4ElementTypeHumanName,
  c4ElementTypePathName,
  componentDiagramElement,
  containerDiagramElement,
  deploymentNodeDiagramElement,
  diagramContainsSubDiagrams,
  diagramDirName,
  diagramTypeHumanName,
  getElementSpecByAlias,
  isDefaultDiagramElementSpec,
  isLegendAlias,
  isRelationshipAlias,
  locationEntityHumanName,
  parseDiagramTypeHumanName,
  personDiagramElement,
  personTypeHumanName,
  relationshipDiagramElement,
  softwareSystemDiagramElement,
  updateDiagramElementsSpecsFromCanvas,
} from './helper/diagram-helper'
export {
  externalLinkVariableToPlaceholder,
  isExternalLink,
  linkableDiagramElement,
  linkLabelFromExternalLink,
  replaceExternalLinkVariables,
} from './helper/diagram-link-helper'
export {
  addObjectsToGroupAndKeepScale,
  getBoundingBox,
  getCanvasPan,
  getSavedZIndex,
  getZIndexOfObject,
  invalidateCanvasCache,
} from './helper/fabric-helper'
export {
  generateSubgraphMarginHackId,
  getGraphHeightInPtFromBB,
  graphvizCoordinatesToPx,
  isC4ElasticContainer,
  isSubgraphInvisibleNodeHack,
  isSubgraphMarginHack,
  svgPathFromGraphvizPos,
} from './helper/graphviz-helper'
export { getSupportedBorderStyle } from './helper/style-helper'
export {
  buildTags,
  getCustomTagsStyle,
  parseTags,
  TAGS_SEPARATOR,
} from './helper/tags-helper'

// Models
export type { AddElementTag } from './models/autogenerated/AddElementTag'
export type { AddElementTagType } from './models/autogenerated/AddElementTagType'
export type { BaseElement } from './models/autogenerated/BaseElement'
export type { Boundary } from './models/autogenerated/Boundary'
export type { BoundaryType } from './models/autogenerated/BoundaryType'
export type { C4ElementType } from './models/autogenerated/C4ElementType'
export type { C4ElementTypeExtended } from './models/autogenerated/C4ElementTypeExtended'
export type { Component } from './models/autogenerated/Component'
export type { ComponentType } from './models/autogenerated/ComponentType'
export type { Container } from './models/autogenerated/Container'
export type { ContainerType } from './models/autogenerated/ContainerType'
export type { DeploymentNode } from './models/autogenerated/DeploymentNode'
export type { DeploymentNodeType } from './models/autogenerated/DeploymentNodeType'
export type { Diagram } from './models/autogenerated/Diagram'
export type { DiagramElementSpec } from './models/autogenerated/DiagramElementSpec'
export type { DiagramElementType } from './models/autogenerated/DiagramElementType'
export type { DiagramOrientation } from './models/autogenerated/DiagramOrientation'
export type { DiagramPlantUML } from './models/autogenerated/DiagramPlantUML'
export type { DiagramSpec } from './models/autogenerated/DiagramSpec'
export type { DiagramsThemeSettings } from './models/autogenerated/DiagramsThemeSettings'
export type { DiagramType } from './models/autogenerated/DiagramType'
export type { ElementType } from './models/autogenerated/ElementType'
export type { Person } from './models/autogenerated/Person'
export type { PersonType } from './models/autogenerated/PersonType'
export type { Position } from './models/autogenerated/Position'
export type { Relationship } from './models/autogenerated/Relationship'
export type { RelationshipType } from './models/autogenerated/RelationshipType'
export type { Shape } from './models/autogenerated/Shape'
export type { ShapeType } from './models/autogenerated/ShapeType'
export type { Size } from './models/autogenerated/Size'
export type { SoftwareSystem } from './models/autogenerated/SoftwareSystem'
export type { SystemType } from './models/autogenerated/SystemType'
