use crate::model::c4_element::C4Elements;
use serde::{Deserialize, Serialize};
use ts_rs::TS;
use wasm_bindgen::prelude::wasm_bindgen;

#[derive(TS)]
#[ts(
  export,
  export_to = "../../../apps/keadex-mina/src/models/autogenerated/"
)]
#[wasm_bindgen(getter_with_clone)]
#[derive(Serialize, Deserialize, Debug, Default, Clone)]
pub struct ProjectLibrary {
  pub elements: C4Elements,
}
