/*!
Model representing settings of a Mina's project.
*/

use crate::model::{ai::ai_settings::AISettings, themes::themes_settings::ThemesSettings};
use serde::{Deserialize, Serialize};
use ts_rs::TS;

pub const NAME: &str = "mina";

#[derive(TS)]
#[ts(
  export,
  export_to = "../../../apps/keadex-mina/src/models/autogenerated/"
)]
#[derive(Default, Serialize, Deserialize, Debug, Clone)]
pub struct ProjectSettings {
  pub root: String,
  pub name: String,
  pub description: String,
  pub version: String,
  #[serde(skip_serializing_if = "Option::is_none")]
  pub ai_settings: Option<AISettings>,
  #[serde(default = "bool::default")]
  pub autosave_enabled: bool,
  pub autosave_interval_seconds: Option<u8>,
  #[serde(skip_serializing_if = "Option::is_none")]
  pub themes_settings: Option<ThemesSettings>,
}
