use crate::model::{project_library::ProjectLibrary, project_settings::ProjectSettings};
use serde::{Deserialize, Serialize};
use ts_rs::TS;
use wasm_bindgen::prelude::wasm_bindgen;

#[derive(TS)]
#[ts(
  export,
  export_to = "../../../apps/keadex-mina/src/models/autogenerated/"
)]
#[wasm_bindgen(getter_with_clone)]
#[derive(Serialize, Deserialize, Debug, Default)]
pub struct Project {
  pub project_settings: ProjectSettings,
  pub project_library: ProjectLibrary,
}
