/*!
Model representing user settings.
*/

use serde::{Deserialize, Serialize};
use ts_rs::TS;
use wasm_bindgen::prelude::wasm_bindgen;

#[derive(TS)]
#[ts(
  export,
  export_to = "../../../apps/keadex-mina/src/models/autogenerated/"
)]
#[wasm_bindgen(getter_with_clone)]
#[derive(Default, Serialize, Deserialize, Debug, Clone)]
pub struct UserSettings {
  pub git_path: Option<String>,
}
