import type { NodeProps } from '@xyflow/react'
import { kebabCase } from 'change-case'
import { JSX } from 'react'

import { getSupportedBorderStyle } from '../../../helper/style-helper'
import { DiagramElementSpec } from '../../../models/autogenerated/DiagramElementSpec'
import { BOX, LEGEND } from '../../../styles/style-constants'
import {
  C4BaseNodeBuilder,
  C4BaseNodeProps,
  withC4BaseNode,
} from '../C4BaseNode/C4BaseNode'
import { C4Node } from '../C4Diagram/C4Diagram'

export const ALIAS = 'legend'
export const NODE_TYPE = 'c4Legend'

export type C4LegendProps = C4BaseNodeProps & {}

type C4LegendNode = C4Node<C4LegendProps, 'c4Legend'>

export function C4LegendNodeBuilder(props: C4LegendProps): C4LegendNode {
  const defaults: DiagramElementSpec = {
    alias: ALIAS,
    position: {
      left: LEGEND.SIZES.LEFT,
      top: LEGEND.SIZES.TOP,
    },
  }
  return {
    ...C4BaseNodeBuilder(props, defaults),
    type: NODE_TYPE,
    draggable: false,
    selectable: false,
    connectable: false,
  }
}

function C4LegendComponent(node: NodeProps<C4LegendNode>) {
  const data = node.data
  // node.
  function renderItem(
    name: string,
    bgColor: string | undefined,
    _borderColor: string | undefined,
    dashed: boolean | undefined,
    textColor: string,
    position: number,
  ): JSX.Element {
    const borderColor = _borderColor ?? bgColor
    const strokeWidth = borderColor ? 1 : 0
    const box = (
      <div
        key={kebabCase(name)}
        style={{
          background: bgColor,
          border: borderColor,
          borderWidth: strokeWidth,
          borderStyle: dashed ? 'dashed' : 'solid',
          width: LEGEND.SIZES.WIDTH - strokeWidth,
          height: LEGEND.SIZES.HEIGHT - strokeWidth,
        }}
      >
        <span
          className="flex items-center h-full"
          style={{
            color: textColor,
            fontSize: LEGEND.FONT.SIZE_ITEM,
            paddingLeft: LEGEND.SIZES.PADDING_LEFT,
          }}
        >
          {name}
        </span>
      </div>
    )
    return box
  }

  function renderItems() {
    const items: JSX.Element[] = []

    items.push(
      renderItem(
        'Person',
        data.renderElementsOptions?.diagramsThemeSettings?.bg_color_person ??
          BOX.COLORS.BG_COLOR_SOFTWARE_SYSTEM_PERSON,
        undefined,
        undefined,
        data.renderElementsOptions?.diagramsThemeSettings?.text_color_person ??
          BOX.COLORS.TEXT_COLOR_SOFTWARE_SYSTEM_PERSON,
        1,
      ),
    )

    items.push(
      renderItem(
        'Person External',
        data.renderElementsOptions?.diagramsThemeSettings
          ?.bg_color_person_ext ??
          BOX.COLORS.BG_COLOR_SOFTWARE_SYSTEM_PERSON_EXT,
        undefined,
        undefined,
        data.renderElementsOptions?.diagramsThemeSettings
          ?.text_color_person_ext ??
          BOX.COLORS.TEXT_COLOR_SOFTWARE_SYSTEM_PERSON_EXT,
        2,
      ),
    )

    items.push(
      renderItem(
        'System',
        data.renderElementsOptions?.diagramsThemeSettings
          ?.bg_color_software_system ??
          BOX.COLORS.BG_COLOR_SOFTWARE_SYSTEM_PERSON,
        undefined,
        undefined,
        data.renderElementsOptions?.diagramsThemeSettings
          ?.text_color_software_system ??
          BOX.COLORS.TEXT_COLOR_SOFTWARE_SYSTEM_PERSON,
        3,
      ),
    )

    items.push(
      renderItem(
        'System External',
        data.renderElementsOptions?.diagramsThemeSettings
          ?.bg_color_software_system_ext ??
          BOX.COLORS.BG_COLOR_SOFTWARE_SYSTEM_PERSON_EXT,
        undefined,
        undefined,
        data.renderElementsOptions?.diagramsThemeSettings
          ?.text_color_software_system_ext ??
          BOX.COLORS.TEXT_COLOR_SOFTWARE_SYSTEM_PERSON_EXT,
        4,
      ),
    )

    items.push(
      renderItem(
        'Container',
        data.renderElementsOptions?.diagramsThemeSettings?.bg_color_container ??
          BOX.COLORS.BG_COLOR_CONTAINER,
        undefined,
        undefined,
        data.renderElementsOptions?.diagramsThemeSettings
          ?.text_color_container ?? BOX.COLORS.TEXT_COLOR_CONTAINER,
        5,
      ),
    )

    items.push(
      renderItem(
        'Container External',
        data.renderElementsOptions?.diagramsThemeSettings
          ?.bg_color_container_ext ?? BOX.COLORS.BG_COLOR_CONTAINER_EXT,
        undefined,
        undefined,
        data.renderElementsOptions?.diagramsThemeSettings
          ?.text_color_container_ext ?? BOX.COLORS.TEXT_COLOR_CONTAINER_EXT,
        6,
      ),
    )

    items.push(
      renderItem(
        'Component',
        data.renderElementsOptions?.diagramsThemeSettings?.bg_color_component ??
          BOX.COLORS.BG_COLOR_COMPONENT,
        undefined,
        undefined,
        data.renderElementsOptions?.diagramsThemeSettings
          ?.text_color_component ?? BOX.COLORS.TEXT_COLOR_COMPONENT,
        7,
      ),
    )

    items.push(
      renderItem(
        'Component External',
        data.renderElementsOptions?.diagramsThemeSettings
          ?.bg_color_component_ext ?? BOX.COLORS.BG_COLOR_COMPONENT_EXT,
        undefined,
        undefined,
        data.renderElementsOptions?.diagramsThemeSettings
          ?.text_color_component_ext ?? BOX.COLORS.TEXT_COLOR_COMPONENT_EXT,
        8,
      ),
    )

    let lastPosition = 8
    if (data.renderElementsOptions?.diagramsThemeSettings?.bg_color_boundary) {
      lastPosition++
      items.push(
        renderItem(
          'Boundary',
          data.renderElementsOptions.diagramsThemeSettings.bg_color_boundary,
          undefined,
          undefined,
          data.renderElementsOptions?.diagramsThemeSettings
            ?.text_color_boundary ?? BOX.COLORS.TEXT_COLOR_BOUNDARY,
          lastPosition,
        ),
      )
    }

    if (
      data.renderElementsOptions?.diagramsThemeSettings
        ?.bg_color_deployment_node
    ) {
      lastPosition++
      items.push(
        renderItem(
          'Deployment Node',
          data.renderElementsOptions.diagramsThemeSettings
            .bg_color_deployment_node,
          undefined,
          undefined,
          data.renderElementsOptions?.diagramsThemeSettings
            ?.text_color_deployment_node ??
            BOX.COLORS.TEXT_COLOR_DEPLOYMENT_NODE,
          lastPosition,
        ),
      )
    }

    if (data.renderElementsOptions?.tags) {
      Object.entries(data.renderElementsOptions.tags).forEach(
        ([_tag, addElementTag], index) => {
          lastPosition++
          items.push(
            renderItem(
              addElementTag.legend_text ?? addElementTag.tag ?? '<no tag>',
              addElementTag.bg_color,
              addElementTag.border_color ??
                (addElementTag.bg_color ? undefined : 'black'),
              getSupportedBorderStyle(addElementTag.border_style)?.name ===
                '"dashed"',
              addElementTag.font_color ?? 'black',
              lastPosition,
            ),
          )
        },
      )
    }

    return items
  }

  return (
    <div className="flex flex-col">
      <div
        className="font-bold"
        style={{
          fontSize: LEGEND.FONT.SIZE_TITLE,
          color: LEGEND.COLOR.TEXT_COLOR_TITLE,
        }}
      >
        LEGEND
      </div>
      <div className="mt-2">{renderItems()}</div>
    </div>
  )
}

export const C4Legend = withC4BaseNode(C4LegendComponent)
