import { render } from '@testing-library/react'
import ProjectTab from './ProjectTab'
import { ProjectSettings } from '../../models/autogenerated/ProjectSettings'
import { SetStateAction } from 'react'

describe('ProjectTab', () => {
  it('should render successfully', () => {
    const { baseElement } = render(
      <ProjectTab
        mode={'edit'}
        setNewProjectSettings={function (
          value: SetStateAction<ProjectSettings | undefined>,
        ): void {
          console.log('test')
        }}
        chooseProjectDirectory={function (): void {
          console.log('test')
        }}
        root={''}
        name={''}
        version={''}
        description={''}
      />,
    )
    expect(baseElement).toBeTruthy()
  })
})
