import {
  IconButton,
  Input,
  Textarea,
  renderButtons,
} from '@keadex/keadex-ui-kit/cross'
import { useState } from 'react'
import { toast } from 'react-toastify'
import { useAppDispatch } from '../../core/store/hooks'
import { saveProject } from '../../core/store/slices/project-slice'
import {
  createProject,
  saveProjectSettings,
} from '../../core/tauri-rust-bridge'
import { MinaError } from '../../models/autogenerated/MinaError'
import { Project } from '../../models/autogenerated/Project'
import { useTranslation } from 'react-i18next'
import { ProjectSettings } from '../../models/autogenerated/ProjectSettings'
import { faFolder } from '@fortawesome/free-solid-svg-icons'
import { dialog } from '@tauri-apps/api'
import { NAME_REGEX, VERSION_REGEX } from '../../constants/regex'

export interface ModalCRUProjectProps {
  mode: 'edit' | 'create'
  project?: Project
  hideModal: () => void
  onProjectCreated?: (projectRoot: string) => void
}

const emptyProjectSettings: ProjectSettings = {
  root: '',
  name: '',
  description: '',
  version: '',
  openai_api_key: '',
}

export const ModalCRUProject = (props: ModalCRUProjectProps) => {
  const AI_ENABLED = JSON.parse(import.meta.env.VITE_AI_ENABLED)

  const { t } = useTranslation()
  const dispatch = useAppDispatch()
  const [newProjectSettings, setNewProjectSettings] = useState<
    ProjectSettings | undefined
  >(
    props.mode === 'edit'
      ? props.project?.project_settings
      : emptyProjectSettings,
  )

  function chooseProjectDirectory() {
    if (newProjectSettings) {
      dialog.open({ directory: true }).then(async (path) => {
        if (Array.isArray(path)) toast.error(t('common.error.invalid_path'))
        else if (path) {
          setNewProjectSettings({
            ...newProjectSettings,
            root: path,
          })
        }
      })
    }
  }

  function handleConfirmClick() {
    if (newProjectSettings) {
      if (props.mode === 'edit') {
        // Editing the project settings
        if (props.project?.project_settings) {
          const newProject: Project = {
            ...props.project,
            project_settings: {
              ...props.project?.project_settings,
              ...newProjectSettings,
            },
          }
          saveProjectSettings(newProjectSettings)
            .then((result) => {
              dispatch(saveProject(newProject))
              toast.info(t('common.info.done'))
              props.hideModal()
            })
            .catch((error: MinaError) => {
              toast.error(error.msg)
            })
        }
      } else {
        // Creating a new project
        createProject(newProjectSettings)
          .then((result) => {
            toast.info(t('common.info.done'))
            props.hideModal()
            if (props.onProjectCreated)
              props.onProjectCreated(newProjectSettings.root)
          })
          .catch((error: MinaError) => {
            toast.error(error.msg)
          })
      }
    }
  }

  if (newProjectSettings) {
    return (
      <div>
        {/* Modal body */}
        <div className="modal__body">
          {props.mode === 'create' && (
            <IconButton
              icon={faFolder}
              onClick={chooseProjectDirectory}
              className="flex"
              classNameIcon="mt-[3px]"
              classNameContent="ml-3"
            >
              {newProjectSettings.root.replace(/ /g, '').length > 0
                ? newProjectSettings.root
                : t('home.chose_project_dir')}
            </IconButton>
          )}

          <Input
            type="text"
            label={`${t('common.name')}*`}
            className="mt-6"
            allowedChars={NAME_REGEX}
            info={`${t('common.allowed_pattern')}: ${NAME_REGEX}`}
            value={newProjectSettings.name}
            onChange={(e) =>
              setNewProjectSettings({
                ...newProjectSettings,
                name: e.target.value,
              })
            }
          />
          <Input
            type="text"
            label={`${t('common.version')}*`}
            className="mt-6"
            allowedChars={VERSION_REGEX}
            info={`${t('common.allowed_pattern')}: ${VERSION_REGEX}`}
            value={newProjectSettings.version}
            onChange={(e) =>
              setNewProjectSettings({
                ...newProjectSettings,
                version: e.target.value,
              })
            }
          />
          <Textarea
            label={`${t('common.description')}*`}
            className="mt-6"
            value={newProjectSettings.description}
            onChange={(e) =>
              setNewProjectSettings({
                ...newProjectSettings,
                description: e.target.value,
              })
            }
          />
          {AI_ENABLED && (
            <Input
              type="text"
              label={t('common.openai_api_key')}
              className="mt-6"
              value={newProjectSettings.openai_api_key ?? ''}
              onChange={(e) =>
                setNewProjectSettings({
                  ...newProjectSettings,
                  openai_api_key: e.target.value,
                })
              }
            />
          )}
        </div>

        {/* Modal footer */}
        <div className="modal__footer">
          {renderButtons([
            {
              key: 'button-cancel',
              children: <span>{t('common.cancel')}</span>,
              'data-te-modal-dismiss': true,
            },
            {
              key: 'button-save',
              children: (
                <span>
                  {props.mode === 'edit'
                    ? t('common.save')
                    : t('common.create')}
                </span>
              ),
              disabled:
                !newProjectSettings.description ||
                !newProjectSettings.name ||
                !newProjectSettings.version ||
                (props.mode === 'create' && !newProjectSettings.root),
              onClick: handleConfirmClick,
            },
          ])}
        </div>
      </div>
    )
  } else {
    return null
  }
}

export default ModalCRUProject
