import {
  C4ElementType,
  Component,
  Container,
  Diagram,
  DiagramElementType,
  DiagramPlantUML,
  DiagramSpec,
  DiagramType,
  Person,
  SoftwareSystem,
} from '@keadex/c4-model-ui-kit'
import { invoke } from '@tauri-apps/api'
import { C4Elements } from '../models/autogenerated/C4Elements'
import { DiagramFormat } from '../models/autogenerated/DiagramFormat'
import { FileSearchResults } from '../models/autogenerated/FileSearchResults'
import { Project } from '../models/autogenerated/Project'
import { ProjectLibrary } from '../models/autogenerated/ProjectLibrary'
import { ProjectSettings } from '../models/autogenerated/ProjectSettings'

/*########################*/
/*    PROJECT COMMANDS    */
/*########################*/
export async function createProject(
  projectSettings: ProjectSettings,
): Promise<ProjectSettings> {
  return invoke('create_project', { projectSettings })
}

export async function openProject(root: string): Promise<Project> {
  return invoke('open_project', { root })
}

export async function closeProject(root: string): Promise<boolean> {
  return invoke('close_project', { root })
}

export async function saveProjectSettings(
  projectSettings: ProjectSettings,
): Promise<ProjectSettings> {
  return invoke('save_project_settings', { projectSettings })
}

export async function search(
  stringToSearch: string,
  includeDiagramsDir: boolean,
  includeLibraryDir: boolean,
  limit: number,
): Promise<FileSearchResults> {
  return invoke('search', {
    stringToSearch,
    includeDiagramsDir,
    includeLibraryDir,
    limit,
  })
}

/*########################*/
/*   DIAGRAMS COMMANDS    */
/*########################*/
export async function listDiagrams(): Promise<{
  [key in DiagramType]: string[]
}> {
  return invoke('list_diagrams')
}

export async function loadDiagram(
  diagramName: string,
  diagramType: DiagramType,
): Promise<Diagram> {
  return invoke('open_diagram', {
    diagramName,
    diagramType,
  })
}

export async function closeDiagram(
  diagramName: string,
  diagramType: DiagramType,
): Promise<Diagram> {
  return invoke('close_diagram', {
    diagramName,
    diagramType,
  })
}

export async function createDiagram(
  diagramName: string,
  diagramType: DiagramType,
): Promise<boolean> {
  return invoke('create_diagram', {
    diagramName,
    diagramType,
  })
}

export async function duplicateDiagram(
  fromDiagramName: string,
  fromDiagramType: DiagramType,
  toDiagramName: string,
  toDiagramType: DiagramType,
): Promise<boolean> {
  return invoke('duplicate_diagram', {
    fromDiagramName,
    fromDiagramType,
    toDiagramName,
    toDiagramType,
  })
}

export async function deleteDiagram(
  diagramName: string,
  diagramType: DiagramType,
): Promise<ProjectLibrary> {
  return invoke('delete_diagram', {
    diagramName,
    diagramType,
  })
}

export async function saveSpecDiagramRawPlantuml(
  diagramName: string,
  diagramType: DiagramType,
  rawPlantuml: string,
  diagramSpec: DiagramSpec,
): Promise<Diagram> {
  return invoke('save_spec_diagram_raw_plantuml', {
    rawPlantuml,
    diagramSpec,
    diagramName,
    diagramType,
  })
}

// export async function saveSpecDiagramParsedPlantuml(
//   diagramName: string,
//   diagramType: DiagramType,
//   diagramPlantuml: DiagramPlantUML,
//   diagramSpec: DiagramSpec
// ): Promise<Diagram> {
//   return invoke('save_spec_diagram_parsed_plantuml', {
//     diagramPlantuml,
//     diagramSpec,
//     diagramName,
//     diagramType,
//   })
// }

export async function exportDiagramToFile(
  diagramName: string,
  diagramType: DiagramType,
  diagramDataUrl: string,
  format: DiagramFormat,
): Promise<string> {
  return invoke('export_diagram_to_file', {
    diagramDataUrl,
    format,
    diagramName,
    diagramType,
  })
}

export async function generatePlantUMLWithAI(
  description: string,
): Promise<string> {
  return invoke('generate_plantuml', {
    description,
  })
}

export async function parsedElementToPlantUML(
  parsedElement: DiagramElementType,
): Promise<string> {
  return invoke('parsed_element_to_plantuml', {
    parsedElement,
  })
}

export async function diagramToLinkString(
  diagramHumanName: string,
  diagramType: DiagramType,
): Promise<string> {
  return invoke('diagram_to_link_string', {
    diagramHumanName,
    diagramType,
  })
}

export async function diagramFromLinkString(
  linkString: string,
): Promise<Diagram> {
  return invoke('diagram_from_link_string', {
    linkString,
  })
}

export async function deserializePlantUMLByString(
  rawPlantuml: string,
): Promise<DiagramPlantUML> {
  return invoke('deserialize_plantuml_by_string', {
    rawPlantuml,
  })
}

export async function diagramNameTypeFromPath(path: string): Promise<Diagram> {
  return invoke('diagram_name_type_from_path', {
    path,
  })
}

/*########################*/
/*    LIBRARY COMMANDS    */
/*########################*/
export async function listLibraryElements(
  filterC4ElementType: C4ElementType,
): Promise<C4Elements> {
  return invoke('list_library_elements', { filterC4ElementType })
}

export async function deleteLibraryElement(
  uuidElement: string,
  elementType: C4ElementType,
): Promise<C4Elements> {
  return invoke('delete_library_element', { uuidElement, elementType })
}

export async function createPerson(person: Person): Promise<ProjectLibrary> {
  return invoke('create_person', { person })
}

export async function updatePerson(person: Person): Promise<ProjectLibrary> {
  return invoke('update_person', { person })
}

export async function createSoftwareSystem(
  softwareSystem: SoftwareSystem,
): Promise<ProjectLibrary> {
  return invoke('create_software_system', { softwareSystem })
}

export async function updateSoftwareSystem(
  softwareSystem: SoftwareSystem,
): Promise<ProjectLibrary> {
  return invoke('update_software_system', { softwareSystem })
}

export async function createContainer(
  container: Container,
): Promise<ProjectLibrary> {
  return invoke('create_container', { container })
}

export async function updateContainer(
  container: Container,
): Promise<ProjectLibrary> {
  return invoke('update_container', { container })
}

export async function createComponent(
  component: Component,
): Promise<ProjectLibrary> {
  return invoke('create_component', { component })
}

export async function updateComponent(
  component: Component,
): Promise<ProjectLibrary> {
  return invoke('update_component', { component })
}

export async function libraryElementTypeFromPath(
  path: string,
): Promise<C4ElementType> {
  return invoke('library_element_type_from_path', { path })
}
