export const LEGEND = {
  COLOR: {
    TEXT_COLOR_TITLE: '#000000',
  },
  FONT: {
    SIZE_TITLE: 12,
    SIZE_ITEM: 10,
  },
  SIZES: {
    TOP: 20,
    LEFT: 20,
    WIDTH: 120,
    HEIGHT: 20,
    PADDING_LEFT: 10,
  },
}

export const ELEMENT = {
  SIZES: {
    DEFAULT_TOP: LEGEND.SIZES.TOP + LEGEND.SIZES.HEIGHT,
    DEFAULT_LEFT: LEGEND.SIZES.LEFT + LEGEND.SIZES.WIDTH + 50,
    BORDER_WIDTH: 1,
  },
  FONT: {
    FAMILY: 'Calibri',
  },
}

export const BOX = {
  COLORS: {
    BG_COLOR_SOFTWARE_SYSTEM_PERSON: '#1168BD',
    BG_COLOR_CONTAINER: '#438DD5',
    BG_COLOR_COMPONENT: '#85BBF0',
    BG_COLOR_SOFTWARE_SYSTEM_PERSON_EXT: '#686868',
    BG_COLOR_CONTAINER_EXT: '#999999',
    BG_COLOR_COMPONENT_EXT: '#CCCCCC',
    BG_COLOR_BOUNDARY: '#FFFFFF',
    BG_COLOR_DEPLOYMENT_NODE: '#FFFFFF',

    BORDER_COLOR_SOFTWARE_SYSTEM_PERSON: '#0F5BA6',
    BORDER_COLOR_CONTAINER: '#3E84C7',
    BORDER_COLOR_COMPONENT: '#7BADDE',
    BORDER_COLOR_SOFTWARE_SYSTEM_PERSON_EXT: '#525252',
    BORDER_COLOR_CONTAINER_EXT: '#8A8A8A',
    BORDER_COLOR_COMPONENT_EXT: '#BDBDBD',
    BORDER_COLOR_BOUNDARY: '#666666',
    BORDER_COLOR_DEPLOYMENT_NODE: '#666666',

    TEXT_COLOR_SOFTWARE_SYSTEM_PERSON: '#FFFFFF',
    TEXT_COLOR_CONTAINER: '#FFFFFF',
    TEXT_COLOR_COMPONENT: '#000000',
    TEXT_COLOR_SOFTWARE_SYSTEM_PERSON_EXT: '#FFFFFF',
    TEXT_COLOR_CONTAINER_EXT: '#FFFFFF',
    TEXT_COLOR_COMPONENT_EXT: '#000000',
    TEXT_COLOR_BOUNDARY: '#333333',
    TEXT_COLOR_DEPLOYMENT_NODE: '#333333',
  },
  SIZES: {
    WIDTH: 220,
    MIN_HEIGHT: 100,
    PADDING_BOTTOM: 15,
    BORDER_RADIUS: 10,
    TOP_LABEL: 20,
    TOP_TAGS: 5,
    TOP_TYPE_TECHNOLOGY: 15,
    TOP_DESCRIPTION: 25,
    PADDING_Y_DESCRIPTION: 10,
  },
  FONT: {
    SIZE: 14,
    SIZE_TAG: 12,
    SIZE_TYPE_TECHNOLOGY: 12,
    SIZE_DESCRIPTION: 10,
  },
}

export const QUEUE = {
  SIZES: {
    SCALE_Y_TAIL_HEAD: 0.3,
  },
}

export const DB = {
  SIZES: {
    SCALE_X_TOP_BOTTOM: 0.15,
  },
}

export const RELATIONSHIP = {
  COLORS: {
    LINE_COLOR: '#828282',
    TEXT_COLOR: '#404040',
  },
  FONT: {
    SIZE_LABEL: 10,
    SIZE_TECHNOLOGY: 10,
  },
  SIZES: {
    PADDING_BACKGROUND: 3,
    RADIUS_DOT: 3,
    SIZE_TRIANGLE: 9,
    STROKE_WIDTH: 1,
  },
  POSITION: {
    DEFAULT_HEAD_ARROW_ANGLE: 90,
  },
}

export const PERSON = {
  SIZES: {
    BORDER_RADIUS: 40,
    HEAD_RADIUS: 45,
  },
}

export const BASE_ELASTIC_CONTAINER = {
  FONT: {
    SIZE_LABEL: 10,
    SIZE_TYPE_TECHNOLOGY: 10,
  },
  SIZES: {
    MIN_WIDTH: 150,
    MIN_HEIGHT: 80,
    PADDING_FOOTER: 10,
    PADDING_BOX: 10,
  },
}

export const BOUNDARY = {
  SIZES: {
    STROKE_DASH_ARRAY: [5, 5],
  },
}
