/**
Generates the default readme file of the Mina project.
*/
pub fn generate_readme_file() -> String {
  String::from("<p align=\"center\">
  <a href=\"https://keadex.dev/en/projects/keadex-mina\" target=\"_blank\"><img src=\"https://raw.githubusercontent.com/keadex/keadex/refs/heads/main/apps/keadex-mina/public/mina-banner.svg\" width=\"100%\" alt=\"Keadex Mina Logo\" /></a>
</p>

# Keadex Mina Project

This is project created with [Keadex Mina](https://keadex.dev/en/projects/keadex-mina), an open source application available for Linux, MacOS, Windows and the web.

## About Keadex Mina

Keadex Mina is based on the **Diagram as Code** concept: you can diagram software architectures by using [C4 Model PlantUML](https://github.com/plantuml-stdlib/C4-PlantUML) code and adjust the rendered result.

Mina is designed to be used in large projects and provides features to organize your diagrams.

## Project Structure

```
📦root
 ┣ 📂diagrams
 ┃ ┣ 📂component
 ┃ ┃ ┣ 📂my-diagram
 ┃ ┃ ┃ ┣ 📜diagram.puml
 ┃ ┃ ┃ ┗ 📜diagram.spec.json
 ┃ ┃ ┗ 📜.gitkeep
 ┃ ┣ 📂container
 ┃ ┣ 📂deployment
 ┃ ┣ 📂dynamic
 ┃ ┣ 📂system-context
 ┃ ┗ 📂system-landscape
 ┣ 📂library
 ┃ ┣ 📜components.json
 ┃ ┣ 📜containers.json
 ┃ ┣ 📜persons.json
 ┃ ┗ 📜software-systems.json
 ┣ 📜.gitignore
 ┣ 📜hooks.js
 ┣ 📜mina.json
 ┗ 📜README.md
```

### `diagrams` folder

Contains a subfolder for each C4 Model diagram type: [Component](https://c4model.com/#ComponentDiagram), [Container](https://c4model.com/#ContainerDiagram), [Deployment](https://c4model.com/#DeploymentDiagram), [Dynamic](https://c4model.com/#DynamicDiagram), [System Context](https://c4model.com/#SystemContextDiagram), [System Landscape](https://c4model.com/#SystemLandscapeDiagram).

Each diagram type subfolder contains a folder for each diagram created by the user.

The folder of a user-created diagram has the following characteristics:

- Folder name: lower-case and dash-case version of the diagram name.
- Folder content:
  - `diagram.puml`: contains the PlantUML code of the diagram.
  - `diagram.spec.json`: contains the diagram specifications generated by Mina (e.g., positions of the elements, custom meta data, etc.).

### `library` folder

Contains a file for each C4 element type can be saved a reused across the user diagrams. Check out the [C4 Model Abstractions documentation](https://c4model.com/#Abstractions) for the details about each element type.

Each JSON file could contain zero or more elements.

Please visit the [library feature documentation](/en/docs/mina/features/library) for further details.

### `.gitignore` file

Contains the default files and folder to be ignored by git.

### `hooks.js` file

This is the entry Javascript file for coding your custom logic to be executed when Mina events are triggered. The default generated file contains an empty function for each supported hook.

Please visit the [hooks feature documentation](/en/docs/mina/features/hooks) for further details.

### `mina.json` file

Contains the project info and settings (name, version, description, OpenAI API Key, etc.).

### `README.md` file

This is the default, auto-generated README file that you can modify to document your Mina project.

## Useful Links

- [Mina Live](https://keadex.dev/mina-live)
- [Website](https://keadex.dev/en/projects/keadex-mina)
- [Documentation](https://keadex.dev/en/docs/mina/introduction)
- [GitHub Repository](https://github.com/keadex/keadex)
")
}
