use std::vec;

use proc_macro::TokenStream;
use quote::quote;
use syn::{
  parse_macro_input, punctuated::Punctuated, token::Comma, FnArg, ItemFn, Pat, ReturnType, Type,
};

fn extract_error_type(return_type: &ReturnType) -> &Type {
  if let ReturnType::Type(_, type_box) = return_type {
    if let Type::Path(type_path) = &**type_box {
      // Ensure it's a Result<T, E>
      if let Some(seg) = type_path.path.segments.last() {
        if seg.ident == "Result" {
          if let syn::PathArguments::AngleBracketed(args) = &seg.arguments {
            if args.args.len() == 2 {
              if let syn::GenericArgument::Type(error_type) = &args.args[1] {
                return error_type;
              }
            }
          }
        }
      }
    }
  }
  panic!("Web Controller must return a Result<T,E>")
}

fn extract_params(args: &Punctuated<FnArg, Comma>) -> Vec<proc_macro2::TokenStream> {
  let mut params = vec![];
  args.iter().for_each(|arg| {
    match arg {
      FnArg::Typed(pat_type) => {
        if let Pat::Ident(ident) = &*pat_type.pat {
          let param_name = &ident.ident;
          params.push(quote! {#param_name});
        }
      }
      _ => {} // Skip `self` for methods
    }
  });
  return params;
}

/// An attribute macro that transforms a Rust function into a JavaScript-callable function.
/// This macro returns an asynchronous function that invokes the original function
/// and converts the success value into a wasm_bindgen::JsValue.
/// It leverages the wasm_bindgen and serde_wasm_bindgen crates,
/// making it useful when you need to return plain JavaScript objects (wasm_bindgen::JsValue
/// generated by serde_wasm_bindgen) instead of JavaScript classes generated by wasm_bindgen.
/// This macro expects a function that returns a Result<T, E>.
#[proc_macro_attribute]
pub fn web_controller(_attr: TokenStream, item: TokenStream) -> TokenStream {
  // Parse the input tokens as a function
  let input_fn = parse_macro_input!(item as ItemFn);

  // Extract function components
  let vis = &input_fn.vis;
  let fn_name = &input_fn.sig.ident;
  let fn_args = &input_fn.sig.inputs;
  let fn_block = &input_fn.block;
  let return_type = &input_fn.sig.output;
  let error_type = extract_error_type(return_type);
  let params = extract_params(fn_args);

  // Generate an async function that wraps the original one and transforms
  // its success value into a wasm_bindgen::JsValue
  let expanded = quote! {
      #[wasm_bindgen]
      #vis async fn #fn_name(#fn_args) -> Result<wasm_bindgen::JsValue, #error_type> {
          async fn original(#fn_args) #return_type #fn_block
          let value = original(#( #params ),*).await?;

          Ok(serde_wasm_bindgen::to_value(&value)?)
      }
  };

  TokenStream::from(expanded)
}
