use proc_macro::TokenStream;
use quote::{quote, ToTokens};
use std::vec;
use syn::parse::Parser;
use syn::punctuated::Punctuated;
use syn::{parse_macro_input, token::Comma, FnArg, ItemFn, Pat, Path, ReturnType, Type};

const WITHOUT_INPUT_TRANSFORMATION_ARG: &str = "without_input_transformation";

fn extract_result_types(return_type: &ReturnType) -> (&Type, &Type) {
  if let ReturnType::Type(_, type_box) = return_type {
    if let Type::Path(type_path) = &**type_box {
      // Ensure it's a Result<T, E>
      if let Some(seg) = type_path.path.segments.last() {
        if seg.ident == "Result" {
          if let syn::PathArguments::AngleBracketed(args) = &seg.arguments {
            if args.args.len() == 2 {
              if let syn::GenericArgument::Type(success_type) = &args.args[0] {
                if let syn::GenericArgument::Type(error_type) = &args.args[1] {
                  return (success_type, error_type);
                }
              }
            }
          }
        }
      }
    }
  }
  panic!("Web Controller must return a Result<T,E>")
}

fn extract_params(
  args: &syn::punctuated::Punctuated<FnArg, Comma>,
) -> (Vec<proc_macro2::TokenStream>, Vec<proc_macro2::TokenStream>) {
  let mut params_name = vec![];
  let mut params_type = vec![];
  args.iter().for_each(|arg| {
    match arg {
      FnArg::Typed(pat_type) => {
        if let Pat::Ident(ident) = &*pat_type.pat {
          let param_name = &ident.ident;
          let param_type = &pat_type.ty;
          params_name.push(quote! { #param_name });
          params_type.push(quote! { #param_type });
        }
      }
      _ => {} // Skip `self` for methods
    }
  });
  return (params_name, params_type);
}

fn extract_args(args: syn::punctuated::Punctuated<syn::Path, Comma>) -> Vec<String> {
  let mut filtered_args = vec![];
  for arg in &args {
    filtered_args.push(arg.to_token_stream().to_string());
  }
  if filtered_args.len() > 0
    && !filtered_args.contains(&WITHOUT_INPUT_TRANSFORMATION_ARG.to_string())
  {
    panic!("Invalid macro arguments")
  }
  return filtered_args;
}

/// An attribute macro that transforms a Rust function into a JavaScript-callable function.
/// This macro returns an asynchronous function that invokes the original function
/// and converts the success value into a wasm_bindgen::JsValue.
/// It leverages the wasm_bindgen and serde_wasm_bindgen crates,
/// making it useful when you need to return plain JavaScript objects (wasm_bindgen::JsValue
/// generated by serde_wasm_bindgen) instead of JavaScript classes generated by wasm_bindgen.
/// This macro expects a function that returns a Result<T, E>.
#[proc_macro_attribute]
pub fn web_controller(attr: TokenStream, item: TokenStream) -> TokenStream {
  // Parse the macro args
  let args = extract_args(
    Punctuated::<Path, syn::Token![,]>::parse_terminated
      .parse(attr)
      .unwrap(),
  );

  // Parse the input tokens as a function
  let input_fn = parse_macro_input!(item as ItemFn);

  // Extract function components
  let vis = &input_fn.vis;
  let fn_name = &input_fn.sig.ident;
  let fn_args = &input_fn.sig.inputs;
  let fn_block = &input_fn.block;
  let return_type = &input_fn.sig.output;
  let (success_type, error_type) = extract_result_types(return_type);
  let (param_names, param_types) = extract_params(fn_args);
  let return_type_string = success_type.to_token_stream().to_string();

  let mut transformed_fn_args = vec![];
  let mut jsvalue_to_obj_stmts = vec![];
  for (index, _fn_arg) in fn_args.iter().enumerate() {
    let param_name = param_names.get(index).unwrap();
    let param_type = param_types.get(index).unwrap();
    let param_type_string = format!("{}", param_type).replace(" ", "");
    transformed_fn_args.push(quote! {
      #[wasm_bindgen::prelude::wasm_bindgen(unchecked_param_type = #param_type_string)]
      #param_name: wasm_bindgen::JsValue
    });
    jsvalue_to_obj_stmts.push(quote! {
          let #param_name: #param_type = serde_wasm_bindgen::from_value(wasm_bindgen::JsValue::from(#param_name)).unwrap();
        });
  }

  let mut new_fn_args = quote! { #fn_args };
  let mut new_fn_jsvalue_to_obj_stmts = quote! {};
  if !args.contains(&WITHOUT_INPUT_TRANSFORMATION_ARG.to_string()) {
    new_fn_args = quote! { #( #transformed_fn_args ),* };
    new_fn_jsvalue_to_obj_stmts = quote! { #( #jsvalue_to_obj_stmts );* };
  }

  // Generate an async function that wraps the original one and transforms
  // its success value into a wasm_bindgen::JsValue
  let expanded = quote! {
      #[wasm_bindgen::prelude::wasm_bindgen(unchecked_return_type = #return_type_string)]
      #vis async fn #fn_name(#new_fn_args) -> Result<wasm_bindgen::JsValue, #error_type> {
          async fn original(#fn_args) #return_type #fn_block

          #new_fn_jsvalue_to_obj_stmts
          let value = original(#( #param_names ),*).await?;

          use serde::Serialize;
          let serializer = serde_wasm_bindgen::Serializer::new().serialize_maps_as_objects(true);
          Ok(value.serialize(&serializer)?)
      }
  };

  TokenStream::from(expanded)
}
