// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AddElementTag { tag?: string, bg_color?: string, font_color?: string, border_color?: string, shadowing?: string, shape?: string, sprite?: string, techn?: string, legend_text?: string, legend_sprite?: string, border_style?: string, border_thickness?: string, }