// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Boundary } from "./Boundary";
import type { Component } from "./Component";
import type { Container } from "./Container";
import type { DeploymentNode } from "./DeploymentNode";
import type { Person } from "./Person";
import type { Relationship } from "./Relationship";
import type { SoftwareSystem } from "./SoftwareSystem";

export type DiagramElementType = { Include: string } | { Comment: string } | { Person: Person } | { SoftwareSystem: SoftwareSystem } | { Container: Container } | { Component: Component } | { Boundary: Boundary } | { DeploymentNode: DeploymentNode } | { Relationship: Relationship };