// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagramElementSpec } from "./DiagramElementSpec";
import type { Shape } from "./Shape";

export interface DiagramSpec { uuid: string, description?: string, elements_specs: Array<DiagramElementSpec>, shapes: Array<Shape>, }