// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";

export interface ElementData { position?: Point, start?: Point, end?: Point, path?: Array<Point>, svg_path?: string, label_position?: Point, }