// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseElement } from "./BaseElement";
import type { PersonType } from "./PersonType";

export interface Person { base_data: BaseElement, person_type?: PersonType, }