// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Position { left?: number, top?: number, z_index?: number, angle?: number, }