// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";
import type { ShapeType } from "./ShapeType";
import type { Size } from "./Size";

export interface Shape { shape_type?: ShapeType, position?: Position, size?: Size, }