[package]
name = "keadex_mina_macro"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6"
serde = "1"
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
