import { DiagramElementType } from '@keadex/c4-model-ui-kit'
import { Project } from '../../models/autogenerated/Project'
import { LibraryElementType } from '../../views/LibraryElement/LibraryElement'

export interface ModalCRULibraryElementProps {
  mode?: 'createLibraryElement' | 'updateLibraryElement' | 'serializer'
  libraryElement?: Partial<LibraryElementType>
  project?: Project
  enableEdit: boolean
  forceUpdate?: () => void
  hideModal: () => void
  onElementCreated?: (element: DiagramElementType) => void
}

export function normalizeLibraryElement(
  libraryElement: LibraryElementType,
): LibraryElementType {
  if (libraryElement.base_data.description === '') {
    libraryElement.base_data.description = undefined
  }
  return libraryElement
}
