import { Diagram } from '../models/autogenerated/Diagram'
import {
  componentDiagramElement,
  containerDiagramElement,
  deploymentNodeDiagramElement,
  personDiagramElement,
} from '../helper/diagram-helper'
import {
  boundaryDiagramElement,
  softwareSystemDiagramElement,
  relationshipDiagramElement,
  getElementSpecByAlias,
} from '../helper/diagram-helper'
import { renderBoundaryDiagramElement } from './boundary-renderer'
import { renderComponentDiagramElement } from './component-renderer'
import { renderContainerDiagramElement } from './container-renderer'
import { renderDeploymentNodeDiagramElement } from './deployment-node-renderer'
import { renderPersonDiagramElement } from './person-renderer'
import { renderRelationshipDiagramElement } from './relationship-renderer'
import { renderSoftwareSystemDiagramElement } from './software-system-renderer'
import C4Legend, { ALIAS as LEGEND_ALIAS } from '../components/C4Legend'
import { Container } from '../models/autogenerated/Container'
import { Component } from '../models/autogenerated/Component'
import { Boundary } from '../models/autogenerated/Boundary'
import { DeploymentNode } from '../models/autogenerated/DeploymentNode'
import { Person } from '../models/autogenerated/Person'
import { Relationship } from '../models/autogenerated/Relationship'
import { SoftwareSystem } from '../models/autogenerated/SoftwareSystem'
import { DiagramSpec } from '../models/autogenerated/DiagramSpec'
import { DiagramElementType } from '../models/autogenerated/DiagramElementType'
import { C4BaseComponent, DiagramListener } from '../components/C4BaseComponent'

export interface RenderElementsOptions {
  skipLegendRendering?: boolean
  skipAddToCanvas?: boolean
}

export const renderDiagram = (
  canvas: fabric.Canvas,
  diagramListener: DiagramListener,
  diagram?: Diagram
): C4BaseComponent[] | undefined => {
  if (canvas && diagram) {
    canvas.diagramListener = diagramListener
    const components = renderElements(
      canvas,
      diagram.diagram_plantuml?.elements,
      diagram.diagram_spec
    )
    restoreZIndex(components)
    return components
  }
  return
}

export const renderElements = (
  canvas: fabric.Canvas | undefined,
  diagramElements: DiagramElementType[] | undefined,
  diagramSpec: DiagramSpec | undefined,
  options?: RenderElementsOptions
): C4BaseComponent[] => {
  const components: C4BaseComponent[] = []
  if (diagramSpec) {
    if (!options || !options.skipLegendRendering) {
      const component = C4Legend(
        getElementSpecByAlias(
          LEGEND_ALIAS,
          undefined,
          undefined,
          undefined,
          diagramSpec
        )
      )
      if (component) {
        components.push(component)
        canvas?.add(component)
      }
    }
    if (diagramElements) {
      for (const element of diagramElements) {
        if (boundaryDiagramElement(element)) {
          const component = renderBoundaryDiagramElement(
            canvas,
            boundaryDiagramElement(element) as Boundary,
            diagramSpec,
            options
          )
          if (component) components.push(component)
        } else if (componentDiagramElement(element)) {
          const component = renderComponentDiagramElement(
            canvas,
            componentDiagramElement(element) as Component,
            diagramSpec,
            options
          )
          if (component) components.push(component)
        } else if (containerDiagramElement(element)) {
          const component = renderContainerDiagramElement(
            canvas,
            containerDiagramElement(element) as Container,
            diagramSpec,
            options
          )
          if (component) components.push(component)
        } else if (deploymentNodeDiagramElement(element)) {
          const component = renderDeploymentNodeDiagramElement(
            canvas,
            deploymentNodeDiagramElement(element) as DeploymentNode,
            diagramSpec,
            options
          )
          if (component) components.push(component)
        } else if (personDiagramElement(element)) {
          const component = renderPersonDiagramElement(
            canvas,
            personDiagramElement(element) as Person,
            diagramSpec,
            options
          )
          if (component) components.push(component)
        } else if (relationshipDiagramElement(element)) {
          const component = renderRelationshipDiagramElement(
            canvas,
            relationshipDiagramElement(element) as Relationship,
            diagramSpec,
            options
          )
          if (component) components.push(component)
        } else if (softwareSystemDiagramElement(element)) {
          const component = renderSoftwareSystemDiagramElement(
            canvas,
            softwareSystemDiagramElement(element) as SoftwareSystem,
            diagramSpec,
            options
          )
          if (component) components.push(component)
        }
      }
    }
  }
  return components
}

const restoreZIndex = (components: fabric.Object[]) => {
  components.forEach((component) => {
    if (
      component.data?.rawDiagramElementSpec?.position?.z_index !== undefined
    ) {
      component.moveTo(component.data.rawDiagramElementSpec.position.z_index)
    }
    if (component.children && component.children.length > 0)
      restoreZIndex(component.children)
  })
}

export default renderDiagram
