#[cfg(feature = "desktop")]
pub mod ai_controller;
#[cfg(feature = "desktop")]
pub mod diagram_controller;
#[cfg(feature = "desktop")]
pub mod hook_controller;
#[cfg(feature = "desktop")]
pub mod library_controller;
#[cfg(feature = "desktop")]
pub mod project_controller;
#[cfg(feature = "desktop")]
pub mod search_controller;
#[cfg(feature = "mina-web-viewer")]
pub mod web_viewer_controller;
